### ISSUE TITLE
should be able to override parameters in Parameters.py using a config file

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#1]
The chapi default parameters are stored in `/usr/share/geni-ch/chapi/chapi/plugins/chapiv1rpc/chapi/Parameters.py`.  We need to be able to override those parameters using a config file.  A file in a config directory like /etc/geni-ch/ would be ideal.

 _Imported from trac ticket [#1](http://trac.gpolab.bbn.com/chapi/ticket/1),  created by chaos on 11-07-2013 at 11:04, last modified: 11-08-2013 at 12:40_

**Comment by tcmitchell** [comment]
Parameters.py now loads a config file. The config file is `/etc/geni-chapi/chapi.ini` unless configured differently via autoconf.

_Trac comment by tmitchel (github user: tcmitchell) on 11-08-2013 at 12:40_
