### ISSUE TITLE
Migrate scripts from geni-portal to geni-ch

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ch#101]
Move scripts that are related to geni-ch from the geni-portal repository to the geni-ch repository.

Examples include:

* `geni-revoke-member-privileges`
* `geni-disable-user`

Determine which scripts in geni-portal/bin directory should be migrated, and move them to the geni-ch repository.

 _Imported from trac ticket [#101](http://trac.gpolab.bbn.com/chapi/ticket/101),  created by tmitchel on 12-02-2013 at 14:10, last modified: 03-31-2015 at 14:14_

**Comment by MarshallBrinn** [comment]
I did a review of all the scripts in geni-portal/bin. Here's what I think:

These should move as is to geni-ch/bin:

add-cenic-of.sql
add-cornell-ig-of.sql
add-cornell-ig.sql
add-dev-signer.sql
add-exo-fiu.sql
add-exo-uh.sql
add-gpo-of.sql
add-gram-bbn.sql
add-i2-of.sql
add-ig-gpo-of.sql
add-ig-kettering.sql
add-ig-northwestern-of.sql
add-ig-northwestern.sql
add-ig-utah-of.sql
add-ig-utahddc-of.sql
add-ig-utahddc.sql
add-illinois-ig-of.sql
add-illinois-ig.sql
add-kansas-ig-of.sql
add-kansas-ig.sql
add-kettering-ig-of.sql
add-max-ig-of.sql
add-max-ig.sql
add-max.sql
add-missouri-ig-of.sql
add-missouri-ig.sql
add-nlr-of.sql
add-nysernet-ig-of.sql
add-nysernet-ig.sql
add-nysernet-of.sql
add-nyu-ig-of.sql
add-nyu-ig.sql
add-sl-of.sql
add-sox-of.sql
add-stanford-ig-of.sql
add-stanford-ig.sql
add-uen-of.sql
add-wisconsin-ig-of.sql
add-wisconsin-ig.sql
add_exo_nicta.sql
add_ig_gpo_am
add_ig_utah_am
add_irods_server
add_irods_test_server
add_pg_uky_am
add_utah_am
archive_log_entry_tables.sh
archive_sa_entry_tables.sh
check_existence_of_accounts
create_standard_services.sh
delete_member.sh
delete_project.sh
delete_slice.sh
geni-add-member-attribute
geni-add-project-member
geni-add-trusted-tool
geni-assert-email
geni-ch-githash
geni-delete-outside-cert
geni-disable-user
geni-enable-user
geni-init-ca
geni-init-services
geni-ops-report
geni-remove-member-attribute
geni-remove-project-member
geni-update-cert-expiration
gmoc_list_contacts
gmoc_list_slices
init-ca
list_assertions.sh
list_privileges.sh
mk-auth-req
populate_am_type_attribute.sql
report_genich_relations 
sign-auth-req
ssh-key-daemon
sync-gram-racks

-- These should move to geni-ch/bin but need a little rework to remove dependencies
-- on account/identity
create_assertion.sh # Need to fix. CH but has dependencies on account

-- These should stay in the portal
Makefile.am # Obviously with lots of edits
do-make-install.sh
geni-export-rspecs
geni-get-ad-rspecs.ini # But needs to call CHAPI from CHAPI I/F not direct database lookup
geni-parse-map-data # Ditto
geni-watch-omni
launch_localam_daemon.sh


--- These should be deleted as obsolete
geniCA
openssl.cnf

-- These should be deleted as part of portal ticket #299 (delete identity and account tables)

activate_account.sh
disable_account.sh
grant_privilege.sh
list_requested_accounts.sh

--- That leaves a few that need more thought, probably discussing together:
geni-manage-maintenance # We need to rethink this: uses one mechanism for portal and CH
