### ISSUE TITLE
Migrate SR certificates from proto-ch to chapi

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ch#102]
Migrate the SR certs directory from the proto-ch repository to the chapi repository. Include the related SQL scripts currently in proto-ch/bin in this migration.

 _Imported from trac ticket [#102](http://trac.gpolab.bbn.com/chapi/ticket/102),  created by tmitchel on 12-02-2013 at 14:12, last modified: 03-31-2015 at 14:14_

**Comment by tcmitchell** [comment]
The certs should go in `data/sr/certs`. SQL scripts should not get moved over, but the data in those scripts should get added to `data/sr/aggdata.csv`. The new SQL scripts will get generated from that data. The aggregate SQL scripts in `proto-ch/bin` can get deleted.

_Trac comment by tmitchel (github user: tcmitchell) on 09-30-2014 at 17:39_

**Comment by MarshallBrinn** [comment]
I think I have this all set.

There are three steps:
1. Move certs that are in the SR into geni-ch/data/sr/certs.
2. Add lines to aggdata.csv with these aggs
3. Modify the SR database to change the location of the certs.

There are a few complications. First, we need to rename some certs to 'new style' nicknames. Specifically:

exo-bbn-am.pem => gpo-eg.pem
exo-fiu-am.pem => fiu-eg.pem
exo-gpo-of.pem => gpo-eg-of.pem
exo-rci-am.pem => renci-eg.pem
exo-uh-am.pem => uh-eg.pem
exosm-am.pem => eg-sm.pem
ig-gpo-cm.pem => gpo-ig-cm.pem
ig-gpo-of.pem => gpo-ig-of.pem
ig-kettering-cm.pem => kettering-ig-cm.pem
ig-northwestern-cm.pem => northwestern-ig-cm.pem
ig-northwestern-of.pem => northwestern-ig-of.pem
ig-utah-cm.pem => utah-ig-cm.pem
ig-utah-of.pem => utah-ig-of.pem
ig-utahddc-cm.pem => utahddc-ig-cm.pem
ig-utahddc-of.pem => utahddc-ig-of.pem
pg-uky-cm.pem => uky-pg.pem
utah-am.pem => utah-pg.pem

Note that ExoSM's nickname is eg-sm, not exo-sm or something more natural. We can fix this if we choose later.

Second, there are a bunch of certs in geni-portal that aren't included in the SR. I'm leaving these in geni-portal for now.

I'm committing the move of certs on a branch. The script files and CSV file will be attached in later comments to this ticket.

**Comment by MarshallBrinn** [comment]
#!/bin/sh
# Commands to move the certs of AMs in the SR from geni-portal to geni-ch repos
mv ~/geni-portal/sr/certs/cenic-of.pem ~/geni-ch/data/sr/certs/cenic-of-pem
mv ~/geni-portal/sr/certs/cornell-ig-cm.pem ~/geni-ch/data/sr/certs/cornell-ig-cm.pem
mv ~/geni-portal/sr/certs/cornell-ig-of.pem ~/geni-ch/data/sr/certs/cornell-ig-of.pem
mv ~/geni-portal/sr/certs/exo-bbn-am.pem ~/geni-ch/data/sr/certs/gpo-eg.pem
mv ~/geni-portal/sr/certs/exo-fiu-am.pem ~/geni-ch/data/sr/certs/fiu-eg.pem
mv ~/geni-portal/sr/certs/exo-gpo-of.pem ~/geni-ch/data/sr/certs/gpo-eg-of.pem
mv ~/geni-portal/sr/certs/exo-rci-am.pem ~/geni-ch/data/sr/certs/renci-eg.pem
mv ~/geni-portal/sr/certs/exo-uh-am.pem ~/geni-ch/data/sr/certs/uh-eg.pem
mv ~/geni-portal/sr/certs/exosm-am.pem ~/geni-ch/data/sr/certs/eg-sm.pem
mv ~/geni-portal/sr/certs/ig-gpo-cm.pem ~/geni-ch/data/sr/certs/gpo-ig-cm.pem
mv ~/geni-portal/sr/certs/ig-gpo-of.pem ~/geni-ch/data/sr/certs/gpo-ig-of.pem
mv ~/geni-portal/sr/certs/ig-kettering-cm.pem ~/geni-ch/data/sr/certs/kettering-ig-cm.pem
mv ~/geni-portal/sr/certs/ig-northwestern-cm.pem ~/geni-ch/data/sr/certs/northwestern-ig-cm.pem
mv ~/geni-portal/sr/certs/ig-northwestern-of.pem ~/geni-ch/data/sr/certs/northwestern-ig-of.pem
mv ~/geni-portal/sr/certs/ig-utah-cm.pem ~/geni-ch/data/sr/certs/utah-ig-cm.pem
mv ~/geni-portal/sr/certs/ig-utah-of.pem ~/geni-ch/data/sr/certs/utah-ig-of.pem
mv ~/geni-portal/sr/certs/ig-utahddc-cm.pem ~/geni-ch/data/sr/certs/utahddc-ig-cm.pem
mv ~/geni-portal/sr/certs/ig-utahddc-of.pem ~/geni-ch/data/sr/certs/utahddc-ig-of.pem
mv ~/geni-portal/sr/certs/illinois-ig-cm.pem ~/geni-ch/data/sr/certs/illinois-ig-cm.pem
mv ~/geni-portal/sr/certs/illinois-ig-of.pem ~/geni-ch/data/sr/certs/illinois-ig-of.pem
mv ~/geni-portal/sr/certs/kansas-ig-cm.pem ~/geni-ch/data/sr/certs/kansas-ig-cm.pem
mv ~/geni-portal/sr/certs/kansas-ig-of.pem ~/geni-ch/data/sr/certs/kansas-ig-of.pem
mv ~/geni-portal/sr/certs/kettering-ig-of.pem ~/geni-ch/data/sr/certs/kettering-ig-of.pem
mv ~/geni-portal/sr/certs/max-ig-cm.pem ~/geni-ch/data/sr/certs/max-ig-cm.pem
mv ~/geni-portal/sr/certs/max-ig-of.pem ~/geni-ch/data/sr/certs/max-ig-of.pem
mv ~/geni-portal/sr/certs/max.pem ~/geni-ch/data/sr/certs/max.pem
mv ~/geni-portal/sr/certs/missouri-ig-cm.pem ~/geni-ch/data/sr/certs/missouri-ig-cm.pem
mv ~/geni-portal/sr/certs/missouri-ig-of.pem ~/geni-ch/data/sr/certs/missouri-ig-of.pem
mv ~/geni-portal/sr/certs/nysernet-ig-cm.pem ~/geni-ch/data/sr/certs/nysernet-ig-cm.pem
mv ~/geni-portal/sr/certs/nysernet-ig-of.pem ~/geni-ch/data/sr/certs/nysernet-ig-of.pem
mv ~/geni-portal/sr/certs/nysernet-of.pem ~/geni-ch/data/sr/certs/nysernet-of.pem
mv ~/geni-portal/sr/certs/nyu-ig-cm.pem ~/geni-ch/data/sr/certs/nyu-ig-cm.pem
mv ~/geni-portal/sr/certs/nyu-ig-of.pem ~/geni-ch/data/sr/certs/nyu-ig-of.pem
mv ~/geni-portal/sr/certs/pg-uky-cm.pem ~/geni-ch/data/sr/certs/uky-pg.pem
mv ~/geni-portal/sr/certs/renci-eg-of.pem ~/geni-ch/data/sr/certs/renci-eg-of.pem
mv ~/geni-portal/sr/certs/sl-of.pem ~/geni-ch/data/sr/certs/sl-of.pem
mv ~/geni-portal/sr/certs/sox-of.pem ~/geni-ch/data/sr/certs/sox-of.pem
mv ~/geni-portal/sr/certs/stanford-ig-cm.pem ~/geni-ch/data/sr/certs/stanford-ig-cm.pem
mv ~/geni-portal/sr/certs/stanford-ig-of.pem ~/geni-ch/data/sr/certs/stanford-ig-of.pem
mv ~/geni-portal/sr/certs/utah-am.pem ~/geni-ch/data/sr/certs/utah-pg.pem
mv ~/geni-portal/sr/certs/wisconsin-ig-cm.pem ~/geni-ch/data/sr/certs/wisconsin-ig-cm.pem
mv ~/geni-portal/sr/certs/wisconsin-ig-of.pem ~/geni-ch/data/sr/certs/wisconsin-ig-of.pem

**Comment by MarshallBrinn** [comment]
-- SQL to modify SR entries for new cert names and locations
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/cenic-of-pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/cenic-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/cornell-ig-cm.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/cornell-ig-cm.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/cornell-ig-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/cornell-ig-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/gpo-eg.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/exo-bbn-am.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/fiu-eg.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/exo-fiu-am.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/gpo-eg-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/exo-gpo-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/renci-eg.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/exo-rci-am.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/uh-eg.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/exo-uh-am.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/eg-sm.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/exosm-am.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/gpo-ig-cm.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/ig-gpo-cm.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/gpo-ig-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/ig-gpo-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/kettering-ig-cm.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/ig-kettering-cm.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/northwestern-ig-cm.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/ig-northwestern-cm.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/northwestern-ig-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/ig-northwestern-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/utah-ig-cm.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/ig-utah-cm.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/utah-ig-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/ig-utah-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/utahddc-ig-cm.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/ig-utahddc-cm.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/utahddc-ig-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/ig-utahddc-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/illinois-ig-cm.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/illinois-ig-cm.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/illinois-ig-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/illinois-ig-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/kansas-ig-cm.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/kansas-ig-cm.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/kansas-ig-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/kansas-ig-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/kettering-ig-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/kettering-ig-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/max-ig-cm.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/max-ig-cm.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/max-ig-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/max-ig-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/max.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/max.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/missouri-ig-cm.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/missouri-ig-cm.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/missouri-ig-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/missouri-ig-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/nysernet-ig-cm.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/nysernet-ig-cm.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/nysernet-ig-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/nysernet-ig-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/nysernet-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/nysernet-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/nyu-ig-cm.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/nyu-ig-cm.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/nyu-ig-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/nyu-ig-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/uky-pg.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/pg-uky-cm.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/renci-eg-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/renci-eg-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/sl-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/sl-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/sox-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/sox-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/stanford-ig-cm.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/stanford-ig-cm.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/stanford-ig-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/stanford-ig-of.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/utah-pg.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/utah-am.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/wisconsin-ig-cm.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/wisconsin-ig-cm.pem';
update service_registry set service_cert = '/usr/share/geni-chapi/sr/certs/wisconsin-ig-of.pem' 
where service_cert = '/usr/share/geni-ch/sr/certs/wisconsin-ig-of.pem';

**Comment by MarshallBrinn** [comment]
Correction - gpo-eg and gpo-renci already in geni-ch (AM and OF). No need to move.
exosm already in geni-ch. Keeping that version with that name, even though the nickname is eg-sm.
