### ISSUE TITLE
non-privileged user gets error on profile page

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#104]
AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method lookup_keys with options {'filter': ['KEY_PRIVATE', 'KEY_PUBLIC', '_GENI_KEY_FILENAME', 'KEY_DESCRIPTION', 'KEY_ID', '_GENI_KEY_MEMBER_UID'], 'match': {'_GENI_KEY_MEMBER_UID': '1f655bba-40da-4b74-b59d-1eb321cc1cf9'}} arguments {} query ME.MAY_LOOKUP_KEYS<-CALLER)

 _Imported from trac ticket [#104](http://trac.gpolab.bbn.com/chapi/ticket/104),  created by phelinek on 12-02-2013 at 14:53, last modified: 12-02-2013 at 15:56_

**Comment by tcmitchell** [comment]
Fixed by return subjects from lookup_keys guard.

_Trac comment by tmitchel (github user: tcmitchell) on 12-02-2013 at 15:56_
