### ISSUE TITLE
non-privileged user gets lookup_slices error looking at member

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#105]
I removed both lead and operator privileges and tried to look at a member. I got the following error:
AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method lookup_slices with options {'match': {'_GENI_PROJECT_UID': '2f91f41e-fd0f-4cb8-893a-354075920ab3'}} arguments {} queries [u'ME.MAY_LOOKUP_SLICES_urn_publicid_IDN_ch1_gpolab_bbn_com_project_ahscaletest<-CALLER', 'ME.MAY_LOOKUP_SLICES<-CALLER'])

 _Imported from trac ticket [#105](http://trac.gpolab.bbn.com/chapi/ticket/105),  created by phelinek on 12-02-2013 at 15:04, last modified: 12-02-2013 at 17:22_

**Comment by tcmitchell** [comment]
Two parts to fix:
 * in chapi, pay attention to whether lookup_slices is called with a project_urn or slice_urn, and then act accordingly
 * in portal, only ask for slice info if the current user is a member of the slice


_Trac comment by tmitchel (github user: tcmitchell) on 12-02-2013 at 17:22_
