### ISSUE TITLE
strange sendmail error

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#109]
On cascade, we see:
```
sendmail: fatal: www-data(33): No recipient addresses found in message header
```

 _Imported from trac ticket [#109](http://trac.gpolab.bbn.com/chapi/ticket/109),  created by ahelsing on 12-02-2013 at 16:00, last modified: 07-11-2014 at 10:48_

**Comment by ahelsing** [comment]
Added some code to the sendmail routine to complain if it gets no to address

_Trac comment by ahelsing on 12-09-2013 at 14:50_

**Comment by tcmitchell** [comment]
Where is this message seen? In a log file? If so, which one.

I see one occurrence of this message in `/var/log/mail.err.1` on cascade:

  mail.err.1:Dec 17 13:34:35 cascade postfix/sendmail[8545]: fatal: phelinek@bbn.com(33): No recipient addresses found in message header

I see no occurrences on nye.

I think this can be closed.

_Trac comment by tmitchel (github user: tcmitchell) on 07-11-2014 at 10:48_
