### ISSUE TITLE
project auditor is allowed to create a slice

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#112]
A project auditor is erroneously allowed to create a slice.

To reproduce:
 - make someone an auditor on a slice
 - As an Admin/Lead, go to the create slice page (where you fill in the slice name. Save the full URL at the top of the page
 - Now in another browser log in as the auditor. On the new project, you will see that you cannot do any project operations - this is correct.
 - Now paste into this browser the full link for the createslice page. The page loads and allows you to submit the request, and the slice is created.

 _Imported from trac ticket [#112](http://trac.gpolab.bbn.com/chapi/ticket/112),  created by ahelsing on 12-03-2013 at 09:04, last modified: 12-03-2013 at 09:46_

**Comment by MarshallBrinn** [comment]
This was mistaken: Pam had Operator privileges. WIthout operator privileges she was not able to create a slice (tested by Marshall and Aaron  on illylrica, cascade and marilac).



_Trac comment by mbrinn (github user: MarshallBrinn) on 12-03-2013 at 09:46_
