### ISSUE TITLE
known errors are too verbose

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#119]
Errors with arguments or authorization raise exceptions that cause stacktraces and go in syslog. That is probably too verbose.
For example, trying to create a 2nd slice of the same name in a project causes a stacktrace in chapi.log and syslog both.

Quiet these down

 _Imported from trac ticket [#119](http://trac.gpolab.bbn.com/chapi/ticket/119),  created by ahelsing on 12-03-2013 at 17:08, last modified: 12-12-2013 at 15:41_

**Comment by ahelsing** [comment]
We need to distinguish user errors from system errors - like 2 base classes.

We need to raise CHAPI errors not arbitrary exceptions.

We should fix the ABAC stuff to distinguish between "I could not look up the subjects specified in the arguments" from "Given the subjects, the caller does not have the needed privilege".


_Trac comment by ahelsing on 12-09-2013 at 09:27_

**Comment by MarshallBrinn** [comment]
This was fixed as part of ticket #117 - we only print stack traces for database errors or system errors (not AuthZ or AuthN or argument errors).

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-12-2013 at 15:41_
