### ISSUE TITLE
A single certificate is used to generate all ABAC assertions

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ch#12]
The config parameter `chapiv1rpc.ch_cert` controls which certificate is used to create ABAC assertions. Consider asserting from more specific entities like the MA and the SA.

 _Imported from trac ticket [#12](http://trac.gpolab.bbn.com/chapi/ticket/12),  created by tmitchel on 11-08-2013 at 11:58, last modified: 07-15-2014 at 13:02_

**Comment by ahelsing** [comment]
Will we want to clean this up when using ABAC credentials for policy?

_Trac comment by ahelsing on 07-15-2014 at 13:02_

**Comment by MarshallBrinn** [comment]
This is OBE with 2014 rework of ABAC assertions.
