### ISSUE TITLE
don't compile ABAC on each CHAPI end-host

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#13]
It's not ideal to compile ABAC in situ on each CHAPI end-host, primarily because it could introduce compile-related discrepancies between portal/CH hosts which are hard to debug.  Is it possible to compile ABAC once and have the CH install simply unpack it?

This would remove the need for `g++`, `autoconf-archive`, and `swig`, on portal/CH nodes.

 _Imported from trac ticket [#13](http://trac.gpolab.bbn.com/chapi/ticket/13),  created by chaos on 11-08-2013 at 12:00, last modified: 11-15-2013 at 08:12_

**Comment by ahelsing** [comment]
Y'all may consider this undesirable, in which case we can talk about that.

If not, there's a question of how to best accomplish it.  My recommendation would be to do something analogous to what we do when we install software via stow in the lab (i'm not suggesting we actually install it via stow, because that would bring it into puppet, which isn't appropriate here).  But the idea is that, on some representative system, you do:
```
./configure --prefix=/usr/share/geni-ch/abac-0.1.5
make
sudo make install
```
then tar up the contents of `/usr/share/geni-ch/abac-0.1.5` (which contain the compiled software now) and put it on our internal webserver.  Then the install script downloads and unpacks that, rather than doing the compile in place.  (And then your installer adds the symlink to /usr/share/geni-ch/abac just as it does now.)

There are other ideas too, but that's the gist of what i would do.


_Trac comment by chaos on 11-08-2013 at 12:06_

**Comment by tcmitchell** [comment]
The catch here is that abac is actually configured with `--prefix=/usr` , so we probably can't really install it into `/usr/share/geni-ch/abac-0.1.5` and expect things to work. Regardless, this part of the installer still needs to change. One path, possibly the easiest, is to install abac as an Ubuntu package. The abac team has a deb package available, although it is for abac-0.1.6. We'll need to test against that package and that version to determine if it is a workable path.

_Trac comment by tmitchel (github user: tcmitchell) on 11-08-2013 at 12:53_

**Comment by tcmitchell** [comment]
I'm going to try using the package available at http://abac.deterlab.net/

_Trac comment by tmitchel (github user: tcmitchell) on 11-08-2013 at 15:14_

**Comment by tcmitchell** [comment]
The abac package appears to work fine. It is installed on the lab server and installed by `install_chapi`. abac is no longer built during the install.

_Trac comment by tmitchel (github user: tcmitchell) on 11-08-2013 at 17:17_
