### ISSUE TITLE
optimize for portal performance

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#132]
Work to optimize system performance. For example:
 - Look for top level API calls that result in multiple calls to get the member UID from the URN and consolidate that into 1 call
 - look for multiple calls to look up CS constants from the DB that could be done once

 _Imported from trac ticket [#132](http://trac.gpolab.bbn.com/chapi/ticket/132),  created by ahelsing on 12-05-2013 at 08:33, last modified: 01-13-2014 at 15:56_

**Comment by ahelsing** [comment]
Find the functions most often called, or which take the longest, or whose cumulative time is the most. That is, search the chapi logs for the Invoked and Return From log messages, grabbing the timestamps and method names.

Some guesses of functions to check: Clearinghouse / Registry, lookup_*_member_info, lookup_slices, lookup_projects, lookup_members


_Trac comment by ahelsing on 12-12-2013 at 09:22_

**Comment by MarshallBrinn** [comment]
See proto-ch ticket 912. I  have a number of tailored CHAPI calls that reduce many calls to one and reduce redundant or unnecessary calls. Performance results in terms of number of CHAPI calls and time for individual typical calls (home, slices, slice, projects, project) are all about halved.

This is all in chapi branch tkt132_performance and proto-ch branch tit912_performance.

We should test this after New Years.

- marshall


_Trac comment by mbrinn (github user: MarshallBrinn) on 12-19-2013 at 14:01_
