### ISSUE TITLE
user gets authorization error on cancel join request

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#137]
Trying to cancel a join request you get:
```
[AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method resolve_pending_request with options {'_dummy': _} arguments {'context_type': 1, 'resolution_status': 2, 'resolution_description': _, 'request_id': '1153'} queries [u'ME.MAY_RESOLVE_PENDING_REQUEST_urn_publicid_IDN_ch1_gpolab_bbn_com_project_ahscaletest<-CALLER', 'ME.MAY_RESOLVE_PENDING_REQUEST<-CALLER'])
```

 _Imported from trac ticket [#137](http://trac.gpolab.bbn.com/chapi/ticket/137),  created by ahelsing on 12-05-2013 at 12:03, last modified: 12-06-2013 at 16:21_

**Comment by MarshallBrinn** [comment]
I have a fix on this ready to go after the upgrade on branch tkt137_join_request

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-05-2013 at 13:32_
