### ISSUE TITLE
install_ch should install the python-lxml package rather than easy_install lxml

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#14]
Software installed into central directories on Ubuntu systems via easy_install is difficult to maintain.  Install the python lxml module by installing the python-lxml package via apt-get, rather than by using easy_install.

 _Imported from trac ticket [#14](http://trac.gpolab.bbn.com/chapi/ticket/14),  created by chaos on 11-08-2013 at 12:10, last modified: 11-15-2013 at 08:10_

**Comment by tcmitchell** [comment]
`chapi` requires a newer version of lxml than is available via apt. Switched over to using pip so that installed files can be tracked. Additionally, set version number to 3.2.4 to control installed version of lxml.

_Trac comment by tmitchel (github user: tcmitchell) on 11-13-2013 at 16:04_
