### ISSUE TITLE
Log service is unguarded

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#146]
calls to the log service have no guards or input argument validity checks

 _Imported from trac ticket [#146](http://trac.gpolab.bbn.com/chapi/ticket/146),  created by ahelsing on 12-06-2013 at 08:04, last modified: 12-12-2013 at 15:42_

**Comment by MarshallBrinn** [comment]
Here's what I propose in terms of log guards argument and invocation checks.  

   def log_event(self, message, attributes, user_id):
   	- Argument check: 
		user_id is valid (exists)
		for each attribute, context_type is valid (1-5) and context_id exists (project for 1, slice for 2, member for 3)
	- Invocation check: 
		- Authority
		- Operator
		- user_id = caller

   def get_log_entries_by_author(self, user_id, num_hours):
	- Argument check: 
		- user_id exists
		- num_hours is a valid positive integer
	- Invocation check:
		user_id = caller

   def get_log_entries_for_context(self, context_type, context_id, num_hours):
	- Argument check: 
		context_type is valid context_type (1-5)
		context_id exists (project for 1, slice for 2, member for 3)
		num_hours is a valid positive integer
	- Invocation check:
		None (Open)

   def get_log_entries_by_attributes(self, attribute_sets, num_hours):
	- Argument check: 
		num_hours is a valid positive integer
	- Invocation check:
		None (Open)

   def get_attributes_for_log_entry(self, event_id):
	- Argument check: 
		event_id exists
	- Invocation check:
		None (Open)




_Trac comment by mbrinn (github user: MarshallBrinn) on 12-10-2013 at 08:16_

**Comment by MarshallBrinn** [comment]
This is fixed as part of ticket 117. There are argument and invocation guards on all calls.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-12-2013 at 15:42_
