### ISSUE TITLE
Respect maintenance mode

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#151]
We should teach the CH to understand and respect maintenance mode - that is, if `/etc/geni-ch/geni_maintenance_outage.msg` exists (and the caller is not an Authority or Operator), then return an error. This can be in the guards perhaps.

The goal is that tools other than the portal are also locked out while the system is in maintenance.

 _Imported from trac ticket [#151](http://trac.gpolab.bbn.com/chapi/ticket/151),  created by ahelsing on 12-08-2013 at 06:54, last modified: 12-12-2013 at 16:11_

**Comment by ahelsing** [comment]
Do this as part of Marshall's refactoring

_Trac comment by ahelsing on 12-09-2013 at 09:23_

**Comment by MarshallBrinn** [comment]
This is checked in with the fixes to ticket #117.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-12-2013 at 15:39_

**Comment by ahelsing** [comment]
This is great.

What message will be included in the error to the user?  The same message displayed in the portal?  A generic message saying the CH is down for awhile?  A generic error?

_Trac comment by sedwards (github user: seledwards) on 12-12-2013 at 16:11_
