### ISSUE TITLE
accept_invitation error

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-ch#153]
Seeing this in the error logs several times:

12/09/2013 04:18:48:INFO    :amsoil:[sav1] Called: <accept_invitation>
12/09/2013 04:18:48:INFO    :chapi:SA: Rahul.Shanbhog-Uma-Raghunath@colostate.edu: Invoked accept_invitation Options {'_dummy': ''} Arguments {'invite_id': '541bb721-ef64-49be-9855-25ba6c685eb8', 'member_id': '54281338-0edd-44f8-b0b3-8d464245242e'}
12/09/2013 04:18:48:ERROR   :chapi:SA: Rahul.Shanbhog-Uma-Raghunath@colostate.edu: Exception: [ARGUMENT] ARGUMENT_ERROR (No invitation with given invite_id 541bb721-ef64-49be-9855-25ba6c685eb8)
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/chapiv1rpc/chapi/SliceAuthority.py", line 752, in accept_invitation
    credentials, options)
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/sarm/SAv1PersistentImplementation.py", line 1792, in accept_invitation
    raise CHAPIv1ArgumentError("No invitation with given invite_id %s" % invite_id)

 _Imported from trac ticket [#153](http://trac.gpolab.bbn.com/chapi/ticket/153),  created by mbrinn on 12-09-2013 at 08:36, last modified: 12-13-2013 at 10:28_

**Comment by MarshallBrinn** [comment]
I think this may be connected to #154 (recently closed). The invitations aren't being placed into the database because of the authorization error on invite_member so they aren't there for the accept, even though the email is already sent with these ID's. 

I suggest leaving this open until we move the latest code to nye and see that it doesn't recur thereafter.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-09-2013 at 08:43_

**Comment by ahelsing** [comment]
This is still a bug - I just reproduced the problem with the latest code.  The invite id was not in the db when I tried to accept the invitation, and I got the same error:

12/11/2013 14:27:30:ERROR   :amsoil:[sav1] [ARGUMENT] ARGUMENT_ERROR (No invitation with given invite_id 0f15b3cf-0c64-422f-acd1-a54e0b4036\
e4)
12/11/2013 14:27:30:ERROR   :amsoil:[sav1] Traceback (most recent call last):
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/chapiv1rpc/chapi/SliceAuthority.py", line 752, in accept_invitation
    credentials, options)
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/sarm/SAv1PersistentImplementation.py", line 1852, in accept_invitation
    raise CHAPIv1ArgumentError("No invitation with given invite_id %s" % invite_id)
CHAPIv1ArgumentError: [ARGUMENT] ARGUMENT_ERROR (No invitation with given invite_id 0f15b3cf-0c64-422f-acd1-a54e0b4036e4)


_Trac comment by phelinek on 12-11-2013 at 15:16_

**Comment by ahelsing** [comment]
I've tried repeatedly and can't reproduce this again.  Possibly the first time I hadn't correctly installed the new code, becauase I reinstalled to get some debug print statements in and after that everything worked.  I'm going to close and if we ever see it again we can re-open

_Trac comment by phelinek on 12-11-2013 at 16:11_
