### ISSUE TITLE
Support certificate revocation

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#171]
Provide a way to revoke certificates
 - operator only?
 - can an experimenter report a lost key / request a new certificate revoking their old one?

Provide a CRL or similar for AMs and others to retrieve

Consider [OCSP](http://www.ietf.org/rfc/rfc2560.txt)

This replaces proto-ch ticket 232

 _Imported from trac ticket [#171](http://trac.gpolab.bbn.com/chapi/ticket/171),  created by ahelsing on 12-11-2013 at 09:38, last modified: 09-09-2014 at 11:57_

**Comment by MarshallBrinn** [comment]
We've worked through the basics of how this should work.

 In short, we generate the user certs by using the CA but signing with the MA's cert and key. We need to revoke the same way

1. Revoke the cert using the MA's cert and key, but using the CA's openssl cnf:

*sudo openssl ca -keyfile /usr/share/geni-ch/ma/ma-key.pem  -cert /usr/share/geni-ch/ma/ma-cert.pem  -config /usr/share/geni-ch/CA/openssl.cnf   -revoke /tmp/jgomes-cert.pem _'
Using configuration from /usr/share/geni-ch/CA/openssl.cnf
Revoking Certificate 0B88.
Data Base Updated

2. Create a CRL. Note that this is a separate CRL from the CA's crl (which we would use to revoke things the CA itself signed):

'''sudo openssl ca -keyfile /usr/share/geni-ch/ma/ma-key.pem  -cert /usr/share/geni-ch/ma/ma-cert.pem  -config /usr/share/geni-ch/CA/openssl.cnf -gencrl -out /usr/share/geni-ch/ma/ma-crl.pem'''
Using configuration from /usr/share/geni-ch/CA/openssl.cnf

3. openssl revoke verification works:

'''cat /usr/share/geni-ch/CA/cacert.pem  /usr/share/geni-ch/ma/ma-cert.pem  /usr/share/geni-ch/ma/ma-crl.pem > /tmp/ca_ma_crl.pem
openssl verify -verbose -CAfile /tmp/ca_ma_crl.pem -crl_check /tmp/rrhain.cert '''
/tmp/rrhain.cert: /CN=ee1bbbb5-95c3-466d-a99a-984005d47564/emailAddress=rrhain@bbn.com
error 23 at 0 depth lookup:certificate revoked

4. Add this line to the /etc/apache2/sites-enabled/ch-ssl in the 443 virtual host:

        SSLCARevocationFile /usr/share/geni-ch/ma/ma-crl.pem

5. Apache revoke verification works:

'_python client.py --url https://ch-mb.gpolab.bbn.com/SA --method lookup_for_member --type SLICE --urn urn:publicid:IDN+ch-mb.gpolab.bbn.com+user+rrhain --cert /tmp/rrhain.cert --key /tmp/rrhain.key*
CREDS = []
OPTIONS = {}
No handlers could be found for logger "client"
RESULT = None
MSG = Unknown SSL error: [Errno 1] _ssl.c:504: error:14094414:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate revoked


_Trac comment by mbrinn (github user: MarshallBrinn) on 08-07-2014 at 13:11_

**Comment by MarshallBrinn** [comment]
New script geni-revoke-member-certificate checked into chapi/chapi/bin, to be installed in /usr/local/sbin.
The defaults are usually good, you just need to say:

sudo geni-revoke-member-certificate --revoke _cert.pem_

What remains before rolling this out is making sure that infra changes the ch-ssl to add the appropriate line pointing to the MA crl, plus making sure that file exists before restarting apache with that change.

I ran the following script on all the development clearinghouses:

echo "1000" > /tmp/crlnumber; sudo chown www-data.www-data /tmp/crlnumber;sudo mv /tmp/crlnumber /usr/share/geni-ch/CA; sudo openssl ca -keyfile /usr/share/geni-ch/ma/ma-key.pem -cert /usr/share/geni-ch/ma/ma-cert.pem -config /usr/share/geni-ch/CA/openssl.cnf -gencrl -out /usr/share/geni-ch/ma/ma-crl.pem

When the time comes, we'll need to do the same on nye.




_Trac comment by mbrinn (github user: MarshallBrinn) on 08-07-2014 at 14:32_

**Comment by ahelsing** [comment]
Some nice-to-haves that I'm not even going to bother making a ticket that is unscheduled for:
 - Log the revocation to syslog
 - Use the DB to fetch the member cert - specify the member ID or username, and inside or outside, and the script gets the cert from the DB for you
  - Or failing that, comments with instructions on doing that manually


_Trac comment by ahelsing on 08-07-2014 at 14:38_

**Comment by MarshallBrinn** [comment]
Should be closed once puppet changes to apache/ch-ssl are in effect.

_Trac comment by mbrinn (github user: MarshallBrinn) on 08-13-2014 at 15:55_

**Comment by tcmitchell** [comment]
Software and configuration changes are ready. Closing this task.

_Trac comment by tmitchel (github user: tcmitchell) on 09-09-2014 at 11:57_
