### ISSUE TITLE
Handle mail attribute with multiple addresses

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#175]
Shibboleth allows the email attribute to contain multiple semi-colon separated email addresses.

Parse this properly and store all the addresses.

Multiple values in attributes are separated by a semicolon, per the  [Shibboleth documentation](https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPAddAttribute).

The [InCommon Federation Attribute Summary](https://www.incommon.org/federation/attributesummary.html) lists which attributes can be multi-valued and which cannot. Most can have multiple values.

We should be parsing the "mail" attribute using a semicolon as a separator. But how to store and use multiple email addresses? That's an interesting question. It may simply mean storing the attribute as it arrives, similar to affiliation, and then parsing that when we need it, which is not too often. A standard routine could turn these multi-valued attributes into an array. When we need a single email address, as is the case for a certificate, we can choose the first one, When we send email, we could send to all asserted email addresses.

This replaces proto-ch ticket 740

 _Imported from trac ticket [#175](http://trac.gpolab.bbn.com/chapi/ticket/175),  created by ahelsing on 12-11-2013 at 09:53, last modified: 01-27-2015 at 10:46_

**Comment by ahelsing** [comment]
givenName is also allowed to be multi valued split by semi-colon. Keeping just the first value would be better than what we do now.

_Trac comment by ahelsing on 09-29-2014 at 13:41_

**Comment by tcmitchell** [comment]
UCLA is sending multiple email addresses ('mail') and multiple first names ('givenName').

chapi gets these values from a client, not from shib directly, so isn't the best place for this to be handled. The shibboleth SP (portal) is the best place to handle these multi-valued attributes.


_Trac comment by tmitchel (github user: tcmitchell) on 10-02-2014 at 08:25_

**Comment by tcmitchell** [comment]
This issue moved back to the portal code because Shibboleth issues are properly handled there. See http://trac.gpolab.bbn.com/proto-ch/ticket/740 for more.

_Trac comment by tmitchel (github user: tcmitchell) on 01-27-2015 at 10:46_
