### ISSUE TITLE
remove easy_install packages from install_ch if they're not needed

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#18]
Investigate whether the following easy_install packages are needed for chapi, and remove them from install_ch if they are not:
```
blinker
pika
flask
Flask-XML-RPC
```

 _Imported from trac ticket [#18](http://trac.gpolab.bbn.com/chapi/ticket/18),  created by chaos on 11-08-2013 at 14:13, last modified: 11-15-2013 at 08:11_

**Comment by tcmitchell** [comment]
flask, Flask-XML-RPC, and blinker are all required.

pika does not appear to be required and has been removed.

_Trac comment by tmitchel (github user: tcmitchell) on 11-11-2013 at 17:20_
