### ISSUE TITLE
Method Context complains about SR and CH calls having no cert

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#193]
When we call the SR or CH, no certificate is supplied. Method Context complains that it got no request certificate.

```
12/17/2013 20:25:36:INFO    :amsoil:[chv1] Called: <get_services>
12/17/2013 20:25:36:INFO    :chapi:MethodContext: No request certificate
12/17/2013 20:25:36:INFO    :chapi:SR: Invoked get_services Options {} Arguments {}
12/17/2013 20:25:36:INFO    :chapi:SR: Result from get_services: {'output': None, 'code': 0, 'value': [{'_GENI_SERVICE_CERT_FILENAME': u'/etc/ssl/certs/ca-gpolab.crt', 'SERVICE_NAME': u'', 'SERVICE_CERT': '-----BEGIN CERTIFICATE-----\nMIID/jCCA2egAwIBAgIJAK9p2JuVcVUrMA0GCSqGSIb3DQEBBQUAMI...
```

 _Imported from trac ticket [#193](http://trac.gpolab.bbn.com/chapi/ticket/193),  created by ahelsing on 12-17-2013 at 20:37, last modified: 12-18-2013 at 09:14_

**Comment by MarshallBrinn** [comment]
Fixed: We now have an optional argument on MethodContext (cert_required) which is true by default but false for SR/CH methods. The (possibly null) cert is passed to the SR/CH methods which ignore it. The only use we'd make of the cert if provided is to extract the email address (in MethodContext). Tested and checked into release-1.2.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-18-2013 at 09:10_
