### ISSUE TITLE
update copyrights for CHAPI to 2014

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#199]
The following files in the CHAPI repo have Raytheon BBN copyrights that end in 2013.  Please update them to say 2014 or a range of years ending in 2014.  Thanks:
```
./chapi/plugins/logging/plugin.py
./chapi/plugins/logging/Logging.py
./chapi/plugins/chapiv1rpc/plugin.py
./chapi/plugins/chapiv1rpc/__init__.py
./chapi/plugins/chapiv1rpc/chapi/MemberAuthority.py
./chapi/plugins/chapiv1rpc/chapi/HandlerBase.py
./chapi/plugins/chapiv1rpc/chapi/Exceptions.py
./chapi/plugins/chapiv1rpc/chapi/GuardBase.py
./chapi/plugins/chapiv1rpc/chapi/DelegateBase.py
./chapi/plugins/chapiv1rpc/chapi/__init__.py
./chapi/plugins/chapiv1rpc/chapi/MethodContext.py
./chapi/plugins/chapiv1rpc/chapi/Clearinghouse.py
./chapi/plugins/chapiv1rpc/chapi/SliceAuthority.py
./chapi/plugins/marm/plugin.py
./chapi/plugins/marm/MAv1Guard.py
./chapi/plugins/marm/MAv1Implementation.py
./chapi/plugins/sarm/SAv1PersistentImplementation.py
./chapi/plugins/sarm/plugin.py
./chapi/plugins/sarm/SAv1Guard.py
./chapi/plugins/csrm/plugin.py
./chapi/plugins/csrm/CredentialStore.py
./chapi/plugins/chrm/plugin.py
./chapi/plugins/chrm/CHDatabaseEngine.py
./chapi/plugins/chrm/CHv1PersistentImplementation.py
./chapi/plugins/chrm/ServiceRegistry.py
./chapi/plugins/chrm/ArgumentCheck.py
./chapi/plugins/chrm/CHv1Guard.py
./chapi/plugins/chrm/ABACGuard.py
./chapi/plugins/chrm/CHv1Implementation.py
./chapi/plugins/pgch/plugin.py
./chapi/plugins/pgch/PGCH.py
./chapi/plugins/pgch/__init__.py
./chapi/tools/mapped_tables.py
./chapi/tools/chapi_scaling.py
./chapi/tools/cs_utils.py
./chapi/tools/dbutils.py
./chapi/tools/guard_utils.py
./chapi/tools/multiclient.py
./chapi/tools/pgch_client.py
./chapi/tools/chapi_log.py
./chapi/tools/dbtest.py
./chapi/tools/portal_client.py
./chapi/tools/__init__.py
./chapi/tools/geni_constants.py
./chapi/tools/chapi_utils.py
./chapi/tools/SA_constants.py
./chapi/tools/ABACManager.py
./chapi/tools/client.py
./chapi/tools/SpeaksFor.py
./chapi/tools/MA_constants.py
./chapi/tools/cert_utils.py
./chapi/tools/geni_utils.py
```
This file says it has no copyright.  Is this a kosher invocation for us?  If so, i can update my script to allow it (or to allow it only for particular named files?):
```
./chapi/plugins/chapiv1rpc/chapi/Memoize.py
```

 _Imported from trac ticket [#199](http://trac.gpolab.bbn.com/chapi/ticket/199),  created by chaos on 01-06-2014 at 11:21, last modified: 01-06-2014 at 16:51_

**Comment by MarshallBrinn** [comment]
Memoize.py IS a valid invocation (it is our code and should be checked for copyright) and we should add a copyright notice to it. I'll handle this one specifically on the develop branch. - Marshall

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-06-2014 at 11:52_

**Comment by MarshallBrinn** [comment]
My mistake, this is not our code but copied from wiki.python.org. See the current file header.

#----------------------------------------------------------------------                                                                                             
# No Copyright                                                                                                                                                      
# This code is from https://wiki.python.org/moin/PythonDecoratorLibrary#Memoize                                                                                     
#----------------------------------------------------------------------                                                                                             

Recommend this file be removed from the copyright notice search (if there is a way of excluding files).

- Marshall



_Trac comment by mbrinn (github user: MarshallBrinn) on 01-06-2014 at 11:54_

**Comment by ahelsing** [comment]
Marshall: will do.

_Trac comment by chaos on 01-06-2014 at 12:09_

**Comment by ahelsing** [comment]
Marshall: done ([GST 5708](http://groups.geni.net/syseng/ticket/5708)).  So all that's left on this ticket is updating the 2013 guys to say 2014.

_Trac comment by chaos on 01-06-2014 at 13:20_

**Comment by tcmitchell** [comment]
Copyright notices have been updated.

_Trac comment by tmitchel (github user: tcmitchell) on 01-06-2014 at 16:50_

**Comment by ahelsing** [comment]
Looks good to me.

_Trac comment by chaos on 01-06-2014 at 16:51_
