### ISSUE TITLE
/usr/share/geni-ch/chapi should be owned by root

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#2]
The install_chapi script installs /usr/share/geni-ch/chapi and its contents as owned by whatever user ran the script.  This should instead be owned by root --- nothing centrally installed should depend on a particular Unix user.

 _Imported from trac ticket [#2](http://trac.gpolab.bbn.com/chapi/ticket/2),  created by chaos on 11-07-2013 at 11:35, last modified: 11-08-2013 at 14:37_

**Comment by ahelsing** [comment]
I believe this is installed by making and unpacking a tarball.  If that's true, and assuming root unpacks the tarball, this may be as simple as running the tar extract with the `o` flag:
```
       -o, --no-same-owner
              do not attempt to restore ownership when extracting; -o exhibits
              this behavior when extracting an archive
```

_Trac comment by chaos on 11-07-2013 at 11:36_

**Comment by tcmitchell** [comment]
Added the '-o' option to tar on both the chapi and abac extractions.

_Trac comment by tmitchel (github user: tcmitchell) on 11-08-2013 at 14:37_
