### ISSUE TITLE
omni-bundle page missing list of projects

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#20]
secure/omni-bundle.php

This page should have a drop-down of your projects.

In my case, the home page shows me a list of projects, but this page does not.

 _Imported from trac ticket [#20](http://trac.gpolab.bbn.com/chapi/ticket/20),  created by ahelsing on 11-08-2013 at 15:07, last modified: 11-19-2013 at 11:57_

**Comment by MarshallBrinn** [comment]
Here's the error from the portal_error.log:

```
[Mon Nov 11 16:35:33 2013] [error] [client 128.89.81.222] PHP Fatal error:  Uncaught exception 'Exception' with message 'Unknown value for DB boolean: 1' in /usr/share/geni-ch/lib/php/db_utils.php:306\nStack trace:\n#0 /var/www/secure/omni-bundle.php(45): convert_boolean(true)\n#1 /var/www/secure/omni-bundle.php(121): project_is_expired(Array)\n#2 {main}\n  thrown in /usr/share/geni-ch/lib/php/db_utils.php on line 306
```

The issue seems to be that the code is getting back an 'f'/'t' from the database and isn't happy turning that into a boolean. I'll keep digging.

_Trac comment by mbrinn (github user: MarshallBrinn) on 11-11-2013 at 16:37_

**Comment by MarshallBrinn** [comment]
Put a fix in db-utils.php to accept either 'f' or (numeric) 0 as false and 't' or (numeric) 1 as true to be compatible with both chap returns and direct database returns.

_Trac comment by mbrinn (github user: MarshallBrinn) on 11-11-2013 at 17:00_
