### ISSUE TITLE
Upgrade CHAPI to Federation API v2

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-ch#204]
We need, at some point, to upgrade CHAPI (the Federation Services API) to V2 (ratified 11/13/2013). When, exactly, we need to do this is unclear. 

But there are some benefits to doing it, at least in part, sooner than later.

Specifically, nothing like the CH/SR call 'get_services' (or 'get_services_of_type') is available in v1. But we can query for services e.g. {match: SERVICE_TYPE=LOGGING} in v2. This will make it much easier for us to build a client (like the revised portal) that can tell what services a given CH has and doesn't have.

I'll lay out a detailed list of all the changes that will need to be made on CHAPI to achieve this upgrade. Some may be done in discrete logical chunks.

My intent is that the new CH be backward compatible with the v1 CH so that no changes to the existing portal be required.

 _Imported from trac ticket [#204](http://trac.gpolab.bbn.com/chapi/ticket/204),  created by mbrinn on 01-08-2014 at 11:46, last modified: 02-03-2014 at 10:56_

**Comment by MarshallBrinn** [comment]
Here's a list of changes to be made to CHAPI in order to make it Federation API v2 compliant:

1. Modify return from GET_VERSION
 * VERSION should be "2" (modification)
 * URN should contain the URN of the service (new)
 * IMPLEMENTATION contains the 'code_version, 'code_url', 'code_release_date', 'site_update' (new)
 * SERVICES should indicate additional (non-default) services provided by services (modification)
 * CREDENTIAL_TYPES should be analogous to AM API (type, version} (modification)
 * SERVICE_TYPES - list of service types provided by registry (SR/CH)
 * API_VERSIONS : Peer implementations of different version of same service
 * FIELDS - INclude of any supplementary plus mandatory fields with non-default semantics

2. Add create method with type argument on SA, MA services

3. Add update method with type argument on SA, MA services

4. Add delete method with type argument on SA, MA services (Note: No delete for slice, only projects)

5. Add lookup method with type argument on CH, SA, MA services

6. Add generic lookup_members, modify_membership, lookup_for_member with type argument in SA

7. Change the MA lookup method to return public for all, identifying for authorized and private for self (or authorities). See page 19 of document for details.

8. Add key_type to key services/types.

9. Change the key lookup call to return public to all and private only as authorized (leaving that field blank otherwise).

10. Ensure all dates are in RFC3339 format (timezone offset must be specified).

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-08-2014 at 12:08_

**Comment by tcmitchell** [comment]
Done and merged.

_Trac comment by tmitchel (github user: tcmitchell) on 02-03-2014 at 10:56_
