### ISSUE TITLE
Add script to create tool certificates

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ch#207]
Tools will need certificates to participate in speaks for authorization. Add a script to easily create these certificates.

Nominally, these certificates should have the email address of the tool developer, maintainer, or operator. The certificates should also have a tool name and instance name in the URN.

For the GPO portal the URN might be: URI:urn:publicid:IDN+ch.geni.net+tool+portal-gpo where "portal" is the tool and "gpo" is the instance.

 _Imported from trac ticket [#207](http://trac.gpolab.bbn.com/chapi/ticket/207),  created by tmitchel on 01-15-2014 at 11:51, last modified: 03-06-2014 at 17:10_

**Comment by ahelsing** [comment]
For specs on tool URNs and certs, see http://groups.geni.net/geni/wiki/GAPI_AM_API_DRAFT#ToolCertificates

_Trac comment by ahelsing on 01-15-2014 at 11:54_

**Comment by tcmitchell** [comment]
Added `geni-sign-tool-csr` to sign CSRs from tool developers.

_Trac comment by tmitchel (github user: tcmitchell) on 03-06-2014 at 17:10_
