### ISSUE TITLE
Logging service needs to handle speaks-for

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ch#209]
The logging service methods need credentials and options arguments to that they can handle speaks-for.

 _Imported from trac ticket [#209](http://trac.gpolab.bbn.com/chapi/ticket/209),  created by tmitchel on 01-17-2014 at 14:54, last modified: 02-21-2014 at 12:19_

**Comment by ahelsing** [comment]
Tom - isn't this fixed?

_Trac comment by ahelsing on 02-20-2014 at 14:09_

**Comment by MarshallBrinn** [comment]
Pretty sure it is: I'll test it now.

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-20-2014 at 14:25_

**Comment by MarshallBrinn** [comment]
yes, this is fixed and tested against the most recent 'develop' branch.

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-20-2014 at 14:37_
