### ISSUE TITLE
lookup_sliver_info needs guards

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#218]
The `lookup_sliver_info` method in the SA has no guards. It should, for privacy reasons if nothing else. Try to do this before there are any clients that know how to talk to that - ie before the new omni is released.

Proposed guards:

 - Admins and Operators can see anything
 - Ordinary people can ask for sliver info by slice (where are slivers for my slice?) and need to be members of that slice
 - Ordinary people can ask for sliver info by `creator_urn` but only for themselves
 - Ordinary people can ask for sliver info by `sliver_urn` if they are the a member of the slivers's slice
 - Otherwise, ordinary people CANNOT ask for
  - all slivers on this aggregate
  - all slivers by creation date or expiration date

 _Imported from trac ticket [#218](http://trac.gpolab.bbn.com/chapi/ticket/218),  created by ahelsing on 01-24-2014 at 14:36, last modified: 01-28-2014 at 12:52_

**Comment by MarshallBrinn** [comment]
Fixed in develop - The above guards are in place for lookup_sliver_info.

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-28-2014 at 12:52_
