### ISSUE TITLE
install script for final install must work from master

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#22]
The install script checks out special dev tags currently

For the 'real' install on nye, this will need to work from master or similar.

 _Imported from trac ticket [#22](http://trac.gpolab.bbn.com/chapi/ticket/22),  created by ahelsing on 11-08-2013 at 16:15, last modified: 11-13-2013 at 17:28_

**Comment by tcmitchell** [comment]
The installer works from the local directory so no longer has a dependency on a particular git branch.

_Trac comment by tmitchel (github user: tcmitchell) on 11-13-2013 at 17:28_
