### ISSUE TITLE
Speaks for raises Exception

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#229]
tools/speaksfor raises an Exception if it gets into determine_Speaks_for with a speaks for option but then can't validate this as a speaks for.

That's not very pretty.

Options:
 1. raise CHAPIv1AuthorizationError
 2. return the original cert, treating this as non-speaks for. Then if the tool is not authorized to perform the action, you'll get an authorization error

 _Imported from trac ticket [#229](http://trac.gpolab.bbn.com/chapi/ticket/229),  created by ahelsing on 02-07-2014 at 10:04, last modified: 02-10-2014 at 13:20_

**Comment by tcmitchell** [comment]
I think it should raise CHAPIv1AuthorizationError (or similar) because the exception states in `determine_speaks_for` are actual authorization errors.

_Trac comment by tmitchel (github user: tcmitchell) on 02-07-2014 at 10:10_

**Comment by ahelsing** [comment]
Sample of the ugly logs you see currently:
```
02/08/2014 15:34:00:ERROR   :chapi:SPEAKSFOR: No speaks-for credential but 'urn:publicid:IDN+ch-ah.gpolab.bbn.com+user+mbrinn' passed option speaking_for = 'urn:publicid:IDN+ch-ah.gpolab.bbn.com+user+ahelsing'
02/08/2014 15:34:00:ERROR   :amsoil:[mav1] Call to known method <get_credentials> failed!
Traceback (most recent call last):
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/flaskrpcs/xmlrpcdispatcher.py", line 69, in _dispatch
    return meth(*params)
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/chapiv1rpc/chapi/MemberAuthority.py", line 205, in get_credentials
    credentials, options, read_only=True) as mc:
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/chapiv1rpc/chapi/MethodContext.py", line 118, in __enter__
    self._options)
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/chrm/ABACGuard.py", line 275, in adjust_client_identity
    return determine_speaks_for(client_cert, credentials, options)
  File "/usr/share/geni-ch/chapi/chapi/tools/SpeaksFor.py", line 84, in determine_speaks_for
    raise Exception("Missing speaks-for credential.")
Exception: Missing speaks-for credential.
```


_Trac comment by ahelsing on 02-08-2014 at 15:54_

**Comment by tcmitchell** [comment]
Speaks-for processing now raises `CHAPIv1AuthorizationError`s so that proper error codes and messages are sent back to the client. This required an overhaul of `MethodContext` to catch processing errors during the set up phase of the `with` block.

_Trac comment by tmitchel (github user: tcmitchell) on 02-10-2014 at 13:20_
