### ISSUE TITLE
determine_speaks_for uses the first speaks-for credential

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ch#230]
`determine_speaks_for` uses the first speaks-for credential it finds in the list. It should collect all speaks-for credentials in the list and allow any to fulfill the authorization proof.

 _Imported from trac ticket [#230](http://trac.gpolab.bbn.com/chapi/ticket/230),  created by tmitchel on 02-07-2014 at 10:13, last modified: 05-28-2014 at 13:09_

**Comment by MarshallBrinn** [comment]
All fixed and tested. I have this merged into a tkt230_*  branch and will merge/push to develop after the upgrade tomorrow PM. 

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-27-2014 at 15:35_
