### ISSUE TITLE
MA helper method `lookup_allowed_member_info` is externally available

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ch#237]
The helper method `lookup_allowed_member_info` should not be available as a public API method. Move it to the delegate.

 _Imported from trac ticket [#237](http://trac.gpolab.bbn.com/chapi/ticket/237),  created by tmitchel on 02-17-2014 at 13:08, last modified: 02-18-2014 at 08:55_

**Comment by ahelsing** [comment]
I don't know if this is relevant, but I see ugly stuff in the logs:
```
02/17/2014 11:34:24:ERROR   :amsoil:[mav1] [SERVER] SERVER_ERROR (list index out of range)
02/17/2014 11:34:24:ERROR   :amsoil:[mav1]   File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/chapiv1rpc/chapi/MemberAuthority.py", line 107, in lookup_allowed_member_info
    mc._session)

  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/marm/MAv1Implementation.py", line 396, in lookup_allowed_member_info
    options, {}, session)

  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/marm/MAv1Implementation.py", line 468, in determine_allowed_match
    subject_type = subjects.keys()[0]

02/17/2014 11:34:24:INFO    :chapi:MA: tmitchel@bbn.com: Result from lookup_allowed_member_info: {'output': '[SERVER] SERVER_ERROR (list index out of range)', 'code': 101, 'value': None}
```

Plus, I see very verbose output that looks like it should be debug:
```
02/17/2014 11:36:25:INFO    :chapi:MA: PUB = {'output': None, 'code': 0, 'value': {u'urn:publicid:IDN+ch.geni.net+user+tmitchel': {'MEMBER_UID': '7f9ba548-8874-43aa-9fcf-c497226cf0ed', '_GENI_MEMBER_SSL_PUBLIC_KEY': 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQD4crCxq62sd6DPYl8kVIkgAQKh7zfUS5UQgei8lKpZhQCxa7Q+yFHExwery2bpHiwjI/2TyC83HhllEIMYpTxAno4WhaIVug/iFWAaIhBKWhbgXhO57H+6acLWGolZjLwqE0jtQQIC5ZW+80nzHsYbbf/mFxawCyNfO57uCzNhuwIDAQAB', '_GENI_MEMBER_INSIDE_PUBLIC_KEY': 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDJ0GndFwB9eidhtj6HSFcW+XBRYINjGIjw7nNuT/IWzuBZQ9sb6SIfYNfjngEmlNVmoWAzA
....
PeAQGrbtW/FurNrN\n0FAJJ4ESXZFR34qgPOaEbm8FsDIe2dQGpaOk/xQTqzc/tjGCg1hOV3QkcHnCrdcV\nFpoZt5WCjYC4r1L9DfAwPatVhxdYiHMxNFbbVrny0s/nPAo=\n-----END CERTIFICATE-----\n', 'MEMBER_URN': u'urn:publicid:IDN+ch.geni.net+user+tmitchel', '_GENI_ENABLE_WIMAX_BUTTON': u'true', 'MEMBER_USERNAME': u'tmitchel'```
}}}

And I suspect these two need to be turned down as well:
```
02/17/2014 11:39:05:INFO    :chapi:MA: ID = {'output': None, 'code': 0, 'value': {}}
02/17/2014 11:39:05:INFO    :chapi:MA: PRIV = {'output': None, 'code': 0, 'value': {}}
```


_Trac comment by ahelsing on 02-17-2014 at 14:39_

**Comment by tcmitchell** [comment]
The call(s) to `lookup_allowed_member_info` are from me, as shown in the log. I was trying things manually using raw XML-RPC. Those errors should be ignored.

_Trac comment by tmitchel (github user: tcmitchell) on 02-17-2014 at 15:10_

**Comment by MarshallBrinn** [comment]
Cleaning up the externally visible method raises an interesting question. According to V2, only "lookup" is visible (which then calls lookup_allowable_member_info or lookup_key_info depending on type. The former of these is new and internal, but the latter is a V1 call and should remain visible. The issue here is that the original methods are wrapped in MethodContext calling the delegate method directly avoids MethodContext.

So far as the verbosity:

1. This will be removed with the new externalization of the Guards and I don't think we need to fix this noel

2 and 3. These have been changed to debug.



_Trac comment by mbrinn (github user: MarshallBrinn) on 02-18-2014 at 08:15_

**Comment by MarshallBrinn** [comment]
We agreed that other than fixing the verbosity of #2 and #3 (info => debug) we will leave lookup_allowed_member_info as a public method. It is guarded and consistent with the semantics of the API . It is unadvertised so no one is likely to stumble on it by accident but no harm will occur if they do call it. Closing as wont fix.

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-18-2014 at 08:55_
