### ISSUE TITLE
get_credentials must return version as a string

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#239]
The version of a credential is a string containing an integer, according to the spec.

Stringify the version number in both the MA and SA

 _Imported from trac ticket [#239](http://trac.gpolab.bbn.com/chapi/ticket/239),  created by ahelsing on 02-18-2014 at 14:34, last modified: 05-23-2014 at 18:15_

**Comment by tcmitchell** [comment]
Changed `geni_version` value from int to string in MA and SA.

_Trac comment by tmitchel (github user: tcmitchell) on 05-23-2014 at 18:15_
