### ISSUE TITLE
test omni 2.4 operations with chapi

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#24]
Ensure that omni 2.4 operates properly with chapi:
 - ~~Generate an outside cert in all 3 ways, download it, and confirm it is reasonable~~
 - ~~download an omni bundle, run omni_configure, and talk to a chapi server~~
  - ~~Manually edit the config to talk to pgch on port 8443~~
 - Run all the usual omni commands:
  - ~~get_ch_version~~
   - ~~clean up fields~~
  - ~~list_aggregates~~
  - ~~listmyslices~~
  - ~~listmykeys~~
  - ~~listslices <username - not you>~~
  - ~~createslice~~
  - ~~getslicecred~~
  - ~~renewslice~~

 _Imported from trac ticket [#24](http://trac.gpolab.bbn.com/chapi/ticket/24),  created by ahelsing on 11-08-2013 at 16:23, last modified: 11-20-2013 at 14:51_

**Comment by tcmitchell** [comment]
Updated description to focus on omni 2.4. Future version of omni will require other testing, and should probably be part of the omni release process rather than the cutover to chapi.

_Trac comment by tmitchel (github user: tcmitchell) on 11-19-2013 at 12:40_

**Comment by tcmitchell** [comment]
Tested `get_ch_version`, `list_aggregates`, `listmyslices` `listslices <other user>` on both 8443 and /PGCH. All work. The fields in `get_ch_version` could stand to be cleaned up.

Here is the current output from `get_ch_version`:
{{{
{   'api': 1.3,
    'code_tag': '0001',
    'gcf-pgch_api': 1.3,
    'hostname': 'ch.geni.net',
    'hrn': 'ch.geni.net',
    'interface': 'registry',
    'peers': {   },
    'url': 'https://ch.geni.net:8443',
    'urn': 'urn:publicid:IDN+ch.geni.net+authority+ch'
}

_Trac comment by tmitchel (github user: tcmitchell) on 11-19-2013 at 13:08_

**Comment by tcmitchell** [comment]
I did download the omni bundle, which created a config for "/PGCH". I manually created a parallel configuration for ":8443/"

_Trac comment by tmitchel (github user: tcmitchell) on 11-19-2013 at 13:10_

**Comment by tcmitchell** [comment]
`createslice` and `renewslice` had already been tested and [repaired](52).

_Trac comment by tmitchel (github user: tcmitchell) on 11-19-2013 at 13:12_

**Comment by tcmitchell** [comment]
`getslicecred` works.

_Trac comment by tmitchel (github user: tcmitchell) on 11-19-2013 at 13:13_

**Comment by tcmitchell** [comment]
`listmykeys` works.

_Trac comment by tmitchel (github user: tcmitchell) on 11-19-2013 at 13:17_

**Comment by tcmitchell** [comment]
Certificate generation via CSR and not CSR works now (see #61).

_Trac comment by tmitchel (github user: tcmitchell) on 11-20-2013 at 14:02_

**Comment by tcmitchell** [comment]
Cleaned up PGCH GetVersion output. Include current git hash as code_tag. Read local authority (ie. hostname) from amsoil config.

_Trac comment by tmitchel (github user: tcmitchell) on 11-20-2013 at 14:50_

**Comment by tcmitchell** [comment]
PGCH from omni looks good. Done.

_Trac comment by tmitchel (github user: tcmitchell) on 11-20-2013 at 14:51_
