### ISSUE TITLE
Slice Authority handler methods mis-defined

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#247]
In the Slice Authority handler, the methods modify_membership, lookup_members,  and lookup_for_member are all missing the initial 'self' argument.

 _Imported from trac ticket [#247](http://trac.gpolab.bbn.com/chapi/ticket/247),  created by ahelsing on 02-28-2014 at 08:44, last modified: 02-28-2014 at 10:34_

**Comment by MarshallBrinn** [comment]
I have a fix for this tested and checked into a side branch (tkt247_sa_methods). Ready to merge for next release. - Marshall

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-28-2014 at 09:37_

**Comment by MarshallBrinn** [comment]
Merged with develop after testing. Fixed.

_Trac comment by mbrinn (github user: MarshallBrinn) on 02-28-2014 at 10:34_
