### ISSUE TITLE
remove hard coded paths

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#25]
I see hard coded paths in a couple spots

```
./chapi/plugins/marm/MAv1Implementation.py:        self.kmcert = '/usr/share/geni-ch/km/km-cert.pem'
./chapi/tools/cert_utils.py:                         '-config', '/usr/share/geni-ch/CA/openssl.cnf', 
./chapi/tools/.bashrc:export GCFHOME=/usr/share/geni-ch/gcf/src
```

 _Imported from trac ticket [#25](http://trac.gpolab.bbn.com/chapi/ticket/25),  created by ahelsing on 11-08-2013 at 16:41, last modified: 03-31-2015 at 14:13_

**Comment by tcmitchell** [comment]
* In browser:chapi/plugins/marm/MAv1Implementation.py the instance variables `kmcert` and `kmkey` appear to be unused. `grep` reveals no references in the entire tree. Remove them.
 * Turn browser:chapi/tools/.bashrc into `.bashrc.in` and let the Makefile replace the paths. See browser:chapi/bin/Makefile.am for a relevant example.
 * Not sure of the best approach to browser:chapi/tools/cert_utils.py.

_Trac comment by tmitchel (github user: tcmitchell) on 03-06-2014 at 08:22_

**Comment by ahelsing** [comment]
try to do this sooner to support transition

_Trac comment by ahelsing on 07-15-2014 at 13:00_

**Comment by MarshallBrinn** [comment]
1. The references to kmcert and kmtool are done.

2.  SAv1PersistentImpementation.py had a reference (by full path) to the MA cert. This is replaced by a call to the "chapi.ma_cert" config parameter.

3. cert_utils.py has a reference to the openssl.cnf. Replaced this with a refeference to the chapi.ssl_config_file parameter.

NOTE: This step must be done ON EACH INSTALLED MACHINE:
* Add these lines to /usr/share/geni-chapi/chapi.ini:
; Location of CHAPI SSL config file                                             
ssl_config_file=/usr/share/geni-ch/CA/openssl.cnf

4. Removed tools/.bashrc. No one seems to be using it.

**Comment by tcmitchell** [comment]
The fix to `/etc/geni-chapi/chapi.ini` does *not* need to be installed on each machine.
