### ISSUE TITLE
Upgrade CHAPI to support GCF 2.5

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-ch#260]
CHAPI references old GCF directory structure (geni.util, etc.). Need to update to support new 2.5 structures.

 _Imported from trac ticket [#260](http://trac.gpolab.bbn.com/chapi/ticket/260),  created by mbrinn on 04-01-2014 at 11:05, last modified: 05-16-2014 at 12:01_

**Comment by MarshallBrinn** [comment]
Changes made and committed on a branch and preliminary tests completed fine. Should test as a group on Thursday and then try to include this in the Wednesday release. 

_Trac comment by mbrinn (github user: MarshallBrinn) on 04-01-2014 at 16:09_

**Comment by tcmitchell** [comment]
Testing complete.

_Trac comment by tmitchel (github user: tcmitchell) on 05-16-2014 at 12:01_
