### ISSUE TITLE
Portal sluggish with externalized policies

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ch#262]
The portal seems sluggish after the [externalized policies modification](232). Looking at the log, `lookup_public_identifying_member_info` takes 5 seconds and generates 363 assertions of which 27 are unique. It sure looks like there's extra work going on there.

 _Imported from trac ticket [#262](http://trac.gpolab.bbn.com/chapi/ticket/262),  created by tmitchel on 04-03-2014 at 11:49, last modified: 04-07-2014 at 13:07_

**Comment by tcmitchell** [comment]
I'm going to de-dupe the list of subjects requested in `lookup_public_identifying_member_info` because the portal sends lots of duplicates. While the portal should be improved, chapi should protect itself from dumb clients.

_Trac comment by tmitchel (github user: tcmitchell) on 04-03-2014 at 11:50_

**Comment by tcmitchell** [comment]
The de-duping change reduces the home page load time by almost 4 seconds, so that's a good start. Marshall will continue the effort to make things a bit more peppy.

_Trac comment by tmitchel (github user: tcmitchell) on 04-03-2014 at 12:11_

**Comment by ahelsing** [comment]
With these changes, time on Home and Projects page is about 1/4 of what it was, and Join a Project is like 10x better.

_Trac comment by ahelsing on 04-07-2014 at 13:07_
