### ISSUE TITLE
write scripts for common queries

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#263]
Write scripts to do common queries
 - project requests by user
 - # users (by IdP)
 - etc

 _Imported from trac ticket [#263](http://trac.gpolab.bbn.com/chapi/ticket/263),  created by ahelsing on 04-07-2014 at 15:37, last modified: 03-31-2015 at 14:15_

**Comment by tcmitchell** [comment]
Added `geni-list-member-projects` to list the project of a member and their role on each project.

_Trac comment by tmitchel (github user: tcmitchell) on 07-09-2014 at 13:02_

**Comment by ahelsing** [comment]
See #317, #329, etc

_Trac comment by ahelsing on 10-28-2014 at 14:15_

**Comment by MarshallBrinn** [comment]
Added script in geni-list-idp-members which prints counts, per IDP (by eppn suffix) of number of members registered at that IDP.

**Comment by MarshallBrinn** [comment]
Added script geni-list-pending-requests to print pending project join requests (project, user, time).

**Comment by MarshallBrinn** [comment]
With these two scripts I close this ticket, having done the two scripts indicated. If we identify more scripts, we should open a ticket for them, specifically.
