### ISSUE TITLE
Filter 'is speaking for' log entries in geni-check-errors

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ch#265]
We get lots of "TOOL is speaking for USER" log messages when using speaks-for. Add these messages to the filtered set in geni-check-errors so that they don't show up when checking for errors.

 _Imported from trac ticket [#265](http://trac.gpolab.bbn.com/chapi/ticket/265),  created by tmitchel on 04-08-2014 at 16:57, last modified: 04-21-2014 at 11:56_

**Comment by ahelsing** [comment]
Sample log message to filter out:
```
04/18/2014 10:04:00:INFO    :chapi:SPEAKSFOR: 'urn:publicid:IDN+ch.geni.net+authority+portal' is speaking for 'urn:publicid:IDN+ch.geni.net+user+tmitchel'
```


_Trac comment by ahelsing on 04-21-2014 at 11:11_

**Comment by ahelsing** [comment]
filtering only messages where the portal is doing speaksfor for now, since any other use right now would be interesting

_Trac comment by ahelsing on 04-21-2014 at 11:56_
