### ISSUE TITLE
Error when clearing project expiration

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#268]
We see an error when setting project expiration to null. It is legal to remove the project expiration by setting it to null.

Add a `DATETIME_OR_NULL` argument type and parse it in ArgumentCheck similarly to `DATETIME`, but allowing no value as valid.

 _Imported from trac ticket [#268](http://trac.gpolab.bbn.com/chapi/ticket/268),  created by ahelsing on 04-15-2014 at 14:11, last modified: 04-17-2014 at 14:51_

**Comment by ahelsing** [comment]
Logs on trying to remove a project expiration:

 04/15/2014 13:32:18:DEBUG   :chapi:SA: ahelsing@geni.net: Invoked update_project Options {'fields': {'PROJECT_DESCRIPTION': _, 'PROJECT_EXPIRATION': _}, '_dummy': 'null'} Arguments {'project_urn': 'urn:publicid:IDN+ch-ah.gpolab.bbn.com+project+ahscaletest'}

 04/15/2014 13:32:18:ERROR   :amsoil:[sav1] [ARGUMENT] ARGUMENT_ERROR (Ill-formed argument of type DATETIME field PROJECT_EXPIRATION: )



_Trac comment by ahelsing on 04-15-2014 at 14:15_

**Comment by tcmitchell** [comment]
Added DATETIME_OR_NULL to ArgumentCheck and to SA_constants.

_Trac comment by tmitchel (github user: tcmitchell) on 04-17-2014 at 14:51_
