### ISSUE TITLE
authorization error on log_event

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#270]
Since the v1.7 upgrade we have dozens of authorization errors in the logs from log_event.

Sample:
```
04/15/2014 11:26:55:INFO    :chapi:SA: lnevers@bbn.com: Invoked create_slice Options {'fields': {'SLICE_PROJECT_URN': 'urn:publicid:IDN+ch.geni.net+project+ln-test', 'SLICE_NAME': 'ill-utahddc'}} Arguments {}
04/15/2014 11:26:55:INFO    :chapi:LOG: lnevers@bbn.com: Invoked log_event Options {'fields': {'SLICE_PROJECT_URN': 'urn:publicid:IDN+ch.geni.net+project+ln-test', 'SLICE_NAME': 'ill-utahddc', '_GENI_SLICE_EMAIL': None}} Arguments {'attributes': {'PROJECT': 'bdf95a2a-65bf-434c-9e35-3b7eeedaea91', 'SLICE': ...
04/15/2014 11:26:55:ERROR   :amsoil:[logv1] [AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method log_event with options {'fields': {'SLICE_PROJECT_URN': 'urn:publicid:IDN+ch.geni.net+project+ln-test', 'SLICE_NAME': 'ill-utahddc', '_GENI_SLICE_EMAIL': None}} arguments {'attributes': {'PROJECT': 'bdf95a2a-65bf-434c-9e35-3b7eeedaea91', 'SLICE': '87660baf-e129-4786-b67a-241d08e652d4'}, 'message': 'Created slice ill-utahddc'} queries ['ME.MAY_LOG_EVENT_urn_publicid_IDN_ch_geni_net_project_ln_test<-CALLER', 'ME.MAY_LOG_EVENT<-CALLER'])
04/15/2014 11:26:55:INFO    :chapi:LOG: lnevers@bbn.com: Result from log_event: {'output': "[AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method log_event with options {'fields': {'SLICE_PROJECT_URN': 'urn:publicid:IDN+ch.geni.net+project+ln-test', 'SLICE_NAME': 'ill-utahddc', '_GENI_S...
04/15/2014 11:26:55:INFO    :chapi:SA: lnevers@bbn.com: Created slice ill-utahddc in project bdf95a2a-65bf-434c-9e35-3b7eeedaea91
04/15/2014 11:26:55:INFO    :chapi:SA: lnevers@bbn.com: Result from create_slice: {'output': '', 'code': 0, 'value': {'SLICE_PROJECT_URN': u'urn:publicid:IDN+ch.geni.net+project+ln-test', 'SLICE_NAME': 'ill-utahddc', 'SLICE_EXPIRED': None, 'SLICE_URN': 'urn:publicid:IDN+ch.geni.net:ln-test+slice+ill-utahd...
```

 _Imported from trac ticket [#270](http://trac.gpolab.bbn.com/chapi/ticket/270),  created by ahelsing on 04-15-2014 at 14:56, last modified: 04-17-2014 at 14:51_

**Comment by ahelsing** [comment]
log_event used to say:
            SubjectInvocationCheck([
                "ME.MAY_LOG_EVENT<-ME.IS_AUTHORITY",
                "ME.MAY_LOG_EVENT<-ME.IS_OPERATOR",
                "ME.MAY_LOG_EVENT_$SUBJECT<-ME.BELONGS_TO_$SUBJECT",
                "ME.MAY_LOG_EVENT_$SUBJECT<-ME.INVOKING_ON_SELF_$SUBJECT",
                ], [assert_user_belongs_to_slice_or_project](assert_user_acting_on_self,),
                                   attribute_extractor),

Now it says:
    "assertions" : [
        "ME.IS_$ROLE_$PROJECT<-CALLER",
        "ME.IS_$ROLE_$SLICE<-CALLER",
    "ME.INVOKING_ON_$MEMBER<-CALLER"
    ],
    "policies" : [
        "ME.MAY_$METHOD<-ME.IS_AUTHORITY",
        "ME.MAY_$METHOD<-ME.IS_OPERATOR",
        "ME.MAY_$METHOD_$SLICE<-ME.BELONGS_TO_$SLICE",
        "ME.MAY_$METHOD_$PROJECT<-ME.BELONGS_TO_$PROJECT",
        "ME.MAY_$METHOD<-ME.INVOKING_ON_$SELF"
        ]

It looks like you used to be able to LOG_EVENT_<user> <- INVOKING_ON_SELF_<user>
And now it is written as MA_LOG_EVENT <- INVOKING_ON_<user>

But does the code that generates these assertions know about the change?
And are all those helper methods still being called (assert_user_....)?
guard_utils.assert_user_acting_on_self still calls it ME.INVOKING_ON_SELF_%s<-CALLER

That looks like a bug to me!

Now the particular log message errors I pulled out appear to be about logging the result of create_slice, where the arguments are SLICE_PROJECT_URN and SLICE_NAME. assert_belongs_to_slice says:
    if label != "SLICE_URN": return

And assert_belongs_to_project says:
    if label != "PROJECT_URN": return

Does that mean that the code skips adding both those assertions? If so, that would explain why this log_event call is not authorized.


_Trac comment by ahelsing on 04-15-2014 at 14:56_

**Comment by tcmitchell** [comment]
I was able to reproduce a `log_event` problem for create slice. Then we put in a fix to pass computed bindings along as a temporary variable instead of overwriting the set of variables available for binding. That fixed the problem.

The set of variables available for binding was being changed midstream when it should not have been.


_Trac comment by tmitchel (github user: tcmitchell) on 04-16-2014 at 15:06_
