### ISSUE TITLE
Clean up email on expiring certificates

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#284]
Clean up the geni-expiring-certificates script's email (see ticket #169) to have the correct URL for re-generating your certificate, cleaner text.

 _Imported from trac ticket [#284](http://trac.gpolab.bbn.com/chapi/ticket/284),  created by ahelsing on 04-23-2014 at 09:55, last modified: 05-06-2014 at 13:03_

**Comment by tcmitchell** [comment]
Done. Pointed to https://portal.geni.net/secure/renewcert.php, a new landing for certificate renewal.

_Trac comment by tmitchel (github user: tcmitchell) on 05-06-2014 at 13:03_
