### ISSUE TITLE
Update wording of expiring certificate email

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ch#294]
Update the wording of the expiring certificate email to this:
```
A GENI certificate belonging to you is going to expire on 2014-06-19.

The expiring certificate is used by tools that run outside the GENI Portal 
(https://portal.geni.net). Examples of affected tools are omni [1] and GENI 
Desktop.

To avoid interruption of your use of GENI via these tools, please follow these
steps before the date listed at the top of the email:

1) Generate a new certificate:

      https://portal.geni.net/secure/renewcert.php

2) Reconfigure any affected tools to use the new certificate.
	To reconfigure omni, see: 
	 	http://trac.gpolab.bbn.com/gcf/wiki/OmniConfigure/Automatic
	No additional action is needed for GENI Desktop.

If you have any questions, please email portal-help@geni.net for further assistance.

Thank you!

[1] http://trac.gpolab.bbn.com/gcf/wiki
```

 _Imported from trac ticket [#294](http://trac.gpolab.bbn.com/chapi/ticket/294),  created by tmitchel on 05-20-2014 at 11:45, last modified: 05-27-2014 at 16:04_
   CCing: gpo-expt-support@...

**Comment by tcmitchell** [comment]
Experimenter support asks that we hold off on wording changes and disable the expiring certificate email until omni-configure works gracefully with the new renewed certificates.

_Trac comment by tmitchel (github user: tcmitchell) on 05-20-2014 at 11:51_

**Comment by ahelsing** [comment]
Vic and I talked and we approve the wording as described in the body of this ticket. We're ready to deploy the ticket wording on the portal, but not ready to enable the cron job.  (We're waiting on the gcf release to complete to enable the cron job.)

_Trac comment by sedwards (github user: seledwards) on 05-27-2014 at 15:39_

**Comment by tcmitchell** [comment]
Email text has been updated.

_Trac comment by tmitchel (github user: tcmitchell) on 05-27-2014 at 16:04_
