### ISSUE TITLE
installation creates empty /usr/share/geni-chapi directory

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#30]
The CHAPI installation creates an empty /usr/share/geni-chapi directory.  Remove this if it's not needed.

 _Imported from trac ticket [#30](http://trac.gpolab.bbn.com/chapi/ticket/30),  created by chaos on 11-12-2013 at 13:02, last modified: 11-15-2013 at 08:12_

**Comment by ahelsing** [comment]
I can't find any direct reference to this in my chapi.git, though i may have just skimmed past it.  When i look in my tau-ceti chapi compile log, i see a bunch of:
```
$ sudo make install
Making install in plugins
make[1]: Entering directory `/home/chaos/chapi/plugins'
make[2]: Entering directory `/home/chaos/chapi/plugins'
make[2]: Nothing to be done for `install-exec-am'.
test -z "/usr/share/geni-chapi/../geni-ch/chapi/chapi/plugins" || /bin/mkdir -p "/usr/share/geni-chapi/../geni-ch/chapi/chapi/plugins"
/bin/mkdir -p '/usr/share/geni-chapi/../geni-ch/chapi/chapi/plugins/marm'
 /usr/bin/install -c -m 644  marm/MANIFEST.json marm/MAv1Guard.py marm/MAv1Implementation.py marm/plugin.py '/usr/share/geni-chapi/../geni-ch/chapi/chapi/plugins/marm'
...
```
I'm suspicious of `/usr/share/geni-chapi/../geni-ch`.  Looks messy, but also i wonder if it's related to whatever's creating the empty directory.


_Trac comment by chaos on 11-12-2013 at 13:04_

**Comment by tcmitchell** [comment]
Ultimately, the chapi software should be installed in its own directory, namely `/usr/share/geni-chapi`. At present, that will probably be too big a shift, so I constructed the automake makefiles to install to the same directory as the installation scripts. That directory is `/usr/share/geni-ch/chapi`. I consider that location to be a short-term destination that should be changed in the future to avoid tangled dependency between chapi and proto-ch.

GNU automake creates the top level directory associated with the project, which is named in the configure.ac file. So it creates `/usr/share/geni-chapi` assuming some files will be installed there. We don't, but I also don't want to figure out how to convince automake to not create that directory. If we ever get to the point of creating a debian package out of chapi, the package would be named `geni-chapi` and would install in `/usr/share/geni-chapi`.

Consider `/usr/share/geni-chapi` to be the long-term goal, and `/usr/share/geni-ch/chapi` to be the short-term solution.

_Trac comment by tmitchel (github user: tcmitchell) on 11-12-2013 at 13:14_

**Comment by tcmitchell** [comment]
`/usr/share/geni-chapi` is no longer empty. Files have started to be directed there by `make install`.

_Trac comment by tmitchel (github user: tcmitchell) on 11-15-2013 at 08:12_
