### ISSUE TITLE
Clean up certificate related files in /tmp

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ch#302]
Files are left in `/tmp` related to certificate creation and/or renewal. Clean these up in the code.

The files match the pattern `/tmp/tmp??????`.

 _Imported from trac ticket [#302](http://trac.gpolab.bbn.com/chapi/ticket/302),  created by tmitchel on 05-28-2014 at 08:37, last modified: 06-03-2014 at 13:39_

**Comment by MarshallBrinn** [comment]
I checked in a fix for this in cert_utils.py (an obvious lack of unlink for a created temp file). I think this nails this problem. But I'd like to keep this open for a few days and see if there's anything else that accumulates. - Marshall

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-28-2014 at 12:54_

**Comment by ahelsing** [comment]
We see an example of a CSR tmpfile being left behind when generating an insider certificate.

_Trac comment by ahelsing on 06-03-2014 at 13:39_

**Comment by ahelsing** [comment]
Putting that issue on a new ticket.

_Trac comment by ahelsing on 06-03-2014 at 13:39_
