### ISSUE TITLE
MA get_credentials must append MA cert

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#303]
When getting the user credential we now use the cert the user provided. That is missing the MA cert, so the cert chain is incomplete.

Append the MA cert to what the user provides.

 _Imported from trac ticket [#303](http://trac.gpolab.bbn.com/chapi/ticket/303),  created by ahelsing on 05-28-2014 at 16:15, last modified: 05-28-2014 at 16:55_

**Comment by ahelsing** [comment]
Symptom is that an AM that only trusts the CA and SA and not the MA but tries to verify all certs in the user credential will fail.

Try this on a FOAM or GRAM instance.

_Trac comment by ahelsing on 05-28-2014 at 16:35_

**Comment by tcmitchell** [comment]
When fixing #299 the intermediate CA certificate was accidentally dropped from the object and target gids in the user credential. Restored the intermediate CA.

_Trac comment by tmitchel (github user: tcmitchell) on 05-28-2014 at 16:55_
