### ISSUE TITLE
PGCH accesses array elements that may be missing

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#305]
Logs show:
```
06/05/2014 00:03:00:ERROR   :amsoil:[pgchv1] [SERVER] SERVER_ERROR (('_GENI_MEMBER_SSL_CERTIFICATE',))
06/05/2014 00:03:00:ERROR   :amsoil:[pgchv1]   File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/pgch/PGCH.py", line 71, in Resolve
    args)

  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/pgch/PGCH.py", line 361, in Resolve
    member_gid = public_info['_GENI_MEMBER_SSL_CERTIFICATE']

06/05/2014 00:03:00:INFO    :chapi:PGCH: ababu@semandex.net: Result from Resolve: {'output': "[SERVER] SERVER_ERROR (('_GENI_MEMBER_SSL_CERTIFICATE',))", 'code': 101, 'value': None}
```

The code calls lookup_identifying_member_info and lookup_public_info, and then assumes that various fields are present in the return. In particular, it assumes it will find _GENI_MEMBER_SSL_CERTIFICATE. Apparently, that is not always true.

While we're there, it looks like some of the return fields are populated with the wrong information.
 * 'uid' is set to 'member_uuid' but should be 'member_name' (the username)
 * 'name' is set to 'member_name' (the username) but should be (I think) the user's name (i.e. "John Smith")

 _Imported from trac ticket [#305](http://trac.gpolab.bbn.com/chapi/ticket/305),  created by ahelsing on 06-05-2014 at 09:30, last modified: 07-22-2014 at 16:55_

**Comment by tcmitchell** [comment]
This error showed up twice in the last 6 weeks (4/17 - 6/5) to two different people:
 06/04/2014 14:16:27:ERROR   :amsoil:[pgchv1]   File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/pgch/PGCH.py", line 71, in Resolve
 06/05/2014 00:03:00:ERROR   :amsoil:[pgchv1]   File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/pgch/PGCH.py", line 71, in Resolve

Not urgent or pressing unless we start seeing it more.

_Trac comment by tmitchel (github user: tcmitchell) on 06-05-2014 at 11:20_

**Comment by tcmitchell** [comment]
Another instance:

 06/21/2014 17:16:33:ERROR   :amsoil:[pgchv1]   File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/pgch/PGCH.py", line 71, in Resolve
    args)

  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/pgch/PGCH.py", line 361, in Resolve
    member_gid = public_info!['_GENI_MEMBER_SSL_CERTIFICATE']


_Trac comment by tmitchel (github user: tcmitchell) on 06-21-2014 at 17:26_

**Comment by ahelsing** [comment]
getting the full displayname meant asking for more identifying info.

_Trac comment by ahelsing on 07-22-2014 at 16:55_
