### ISSUE TITLE
Investigate "QueuePool limit of size 5 overflow 10 reached" error

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ch#307]
We had a number of occurrences of an error via SQLAlchemy:

 `TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30`

Investigate how to configure the QueuePool and what causes it to be exceeded.

 _Imported from trac ticket [#307](http://trac.gpolab.bbn.com/chapi/ticket/307),  created by tmitchel on 06-06-2014 at 17:02, last modified: 03-04-2015 at 09:47_

**Comment by MarshallBrinn** [comment]
This hasn't happened in many months (I've been checking the logs periodically). Closing.
