### ISSUE TITLE
installation creates /usr/share/geni-ch/.bashrc

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#31]
The install_ch script creates `/usr/share/geni-ch/.bashrc`, which is confusing.  I believe this script is an example bashrc, so it should be installed somewhere which makes that more clear, e.g. `/etc/geni-chapi/example-bashrc` to match other similar files.

 _Imported from trac ticket [#31](http://trac.gpolab.bbn.com/chapi/ticket/31),  created by chaos on 11-12-2013 at 13:16, last modified: 02-05-2015 at 17:04_

**Comment by ahelsing** [comment]
Changed description because of Tom's explanation on #30 for why `/etc/geni-chapi/` is correct for CHAPI config files.

_Trac comment by chaos on 11-12-2013 at 13:22_

**Comment by tcmitchell** [comment]
The file `tools/.bashrc` appears to be vestigial. It was used during development but is no longer used.

_Trac comment by tmitchel (github user: tcmitchell) on 02-05-2015 at 16:53_

**Comment by tcmitchell** [comment]
`tools/.bashrc` was installed in two places during the `make install`:
 * `/usr/share/geni-ch/chapi/chapi/tools/.bashrc`
 * `/usr/share/geni-ch/.bashrc`

We'll want to remove those on the next software update.

_Trac comment by tmitchel (github user: tcmitchell) on 02-05-2015 at 16:58_

**Comment by tcmitchell** [comment]
`tools/.bashrc` has been removed. Mentions of it in Makefile and install scripts have also been removed.

_Trac comment by tmitchel (github user: tcmitchell) on 02-05-2015 at 17:04_
