### ISSUE TITLE
Add indices to critical tables to improve query  performance

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-ch#311]
After analyzing the results from pgBadger, we seem to have found several candidates for indices that will improve query performance: 

create index ma_member_attribute_name_value on ma_member_attribute(name, value);
create index sa_slice_member_member_id on sa_slice_member(member_id);

create index logging_entry_event_time on logging_entry(event_time);
create index logging_entry_attribute_event_id on logging_entry_attribute(event_id);

 _Imported from trac ticket [#311](http://trac.gpolab.bbn.com/chapi/ticket/311),  created by mbrinn on 06-13-2014 at 10:38, last modified: 07-11-2014 at 11:18_

**Comment by MarshallBrinn** [comment]
Indices added Will close ticket when we analyze performance improvement.

_Trac comment by mbrinn (github user: MarshallBrinn) on 06-13-2014 at 11:12_

**Comment by tcmitchell** [comment]
Performance is improved. This task is complete.

_Trac comment by tmitchel (github user: tcmitchell) on 07-11-2014 at 11:18_
