### ISSUE TITLE
Make a script to dump the list of everyone with a portal account

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#317]
Experimenter support regularly needs the output of this file:
```
sudo -u www-data /usr/local/bin/geni-ops-report -u portal -P /usr/sysadmin/etc/portal_password -g > accounts.csv
```

We use this to identify who has accounts.  And particularly for tutorials we use it to determine which attendees have accounts and what their email and/or username is.

 _Imported from trac ticket [#317](http://trac.gpolab.bbn.com/chapi/ticket/317),  created by sedwards on 07-16-2014 at 11:49, last modified: 03-04-2015 at 09:47_
   CCing: gpo-expt-support@...

**Comment by ahelsing** [comment]
needed for transition so we don't need SQL access

_Trac comment by ahelsing on 07-16-2014 at 11:56_

**Comment by tcmitchell** [comment]
I'm not sure what the action is on this ticket. What do you need that the `geni-ops-report` script is not providing?


_Trac comment by tmitchel (github user: tcmitchell) on 02-24-2015 at 11:56_

**Comment by MarshallBrinn** [comment]
Closing. The script does what it does and seems to satisfy any requirements that have been identified.
