### ISSUE TITLE
Determine whether to upgrade to abac 0.1.7

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-ch#321]
We are currently using libabac 0.1.5 and have effectively disabled its use in many places (most notably the query engine) because of memory leak and corruption issues.

The latest version of libabac, 0.1.7, seems to address these leak/corruption issues.

It does appear to be 60-80% slower than the current home-grown implementation of ABAC. We need to work with ISI to see if something can be done to improve the speed and whether it makes sense to change CHAPI over to libabac 0.1.17.

 _Imported from trac ticket [#321](http://trac.gpolab.bbn.com/chapi/ticket/321),  created by mbrinn on 08-04-2014 at 09:42, last modified: 08-04-2014 at 09:42_

**Comment by tcmitchell** [comment]
As of [release 2.12](https://github.com/GENI-NSF/geni-ch/releases/tag/v2.12), issue #467, and pull request #495, the clearinghouse no longer relies on libabac.
