### ISSUE TITLE
Make member_enabled attribute public on members

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#322]
Currently clients cannot tell if a member is disabled. The only symptom is that you cannot lookup SSH keys for a disabled user.

Options include hiding disabled users, or making public the fact that a member is disabled and allowing clients to do what they want.

Easiest for now is to make public that a member is disabled.

 _Imported from trac ticket [#322](http://trac.gpolab.bbn.com/chapi/ticket/322),  created by ahelsing on 08-05-2014 at 12:11, last modified: 09-08-2014 at 13:11_

**Comment by MarshallBrinn** [comment]
This is fixed and tested on marilac. It now returns a boolean for _GENI_MEMBER_ENABLED for all member queries as public info.
Ready to merge into develop.

_Trac comment by mbrinn (github user: MarshallBrinn) on 08-05-2014 at 13:15_

**Comment by ahelsing** [comment]
merged onto develop

_Trac comment by ahelsing on 08-05-2014 at 16:55_

**Comment by ahelsing** [comment]
Test by 
 - explicit lookup public info and see what comes back, OR simply 
 - test http://trac.gpolab.bbn.com/proto-ch/ticket/1124

_Trac comment by ahelsing on 09-08-2014 at 13:11_
