### ISSUE TITLE
Modify Slice Membership with Speaks for bug

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#325]
I think I've IDed a CHAPI / speaksfor bug.

Hussam has been using speaks for on the GENI Desktop.

Logs show this:
```
09/10/2014 14:38:19:INFO    :amsoil:[sav1] Called: <modify_slice_membership>
09/10/2014 14:38:19:INFO    :chapi:SPEAKSFOR: 'urn:publicid:IDN+ch.geni.net+tool+genidesktop-uky' is speaking for 'urn:publicid:IDN+ch.geni.net+user+hussamn'
09/10/2014 14:38:19:INFO    :chapi:SA: hussam.nasir@uky.edu: Invoked modify_slice_membership Options {'members_to_add': [{'SLICE_MEMBER': 'urn:publicid:IDN+ch.geni.net+user+moasci2', 'SLICE_ROLE': 'MEMBER'}, {'SLICE_MEMBER': 'urn:publicid:IDN+ch.geni.net+user+ywsong2', 'SLICE_ROLE': 'MEMBER'}, {'SLICE_MEMBER':...
....
09/10/2014 14:38:19:INFO    :chapi:LOG: genidesktop-admins@netlab.uky.edu: Invoked log_event Options {} Arguments {'attributes': {'PROJECT': 'a45a9d08-59be-4b18-a67a-d42b1a925b9b', 'MEMBER': '5dc196f2-2ea0-4e8a-9d04-219f12583388', 'SLICE': '1d6ef2b9-3044-4c18-b5f9-c2c176bc40f5'}, 'message': u'Hussamuddin Nasir Added member ...
09/10/2014 14:38:19:ERROR   :amsoil:[logv1] [AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method log_event with options {} arguments {'attributes': {'PROJECT': 'a45a9d08-59be-4b18-a67a-d42b1a925b9b', 'MEMBER': '5dc196f2-2ea0-4e8a-9d04-219f12583388', 'SLICE': '1d6ef2b9-3044-4c18-b5f9-c2c176bc40f5'}, 'message': u'Hussamuddin Nasir Added member Yongwook Song in role MEMBER to slice hussamchoice'} queries [u'ME.MAY_LOG_EVENT_urn_publicid_IDN_ch_geni_net_user_ywsong2<-CALLER', 'ME.MAY_LOG_EVENT<-CALLER'])
09/10/2014 14:38:19:INFO    :chapi:LOG: genidesktop-admins@netlab.uky.edu: Result from log_event: {'output': "[AUTHORIZATION] AUTHORIZATION_ERROR (Caller not authorized to call method log_event with options {} arguments {'attributes': {'PROJECT': 'a45a9d08-59be-4b18-a67a-d42b1a925b9b', 'MEMBER': '5dc196f2-2ea0-4e8a-9d04-219...
09/10/2014 14:38:19:INFO    :chapi:SA: hussam.nasir@uky.edu: Hussamuddin Nasir Added member Yongwook Song in role MEMBER to slice hussamchoice in project UKGENI
....
```

I believe that Hussam used GENI Desktop to call modify_slice_membership, which in turn tries to log an event. But somehow the log service is called without the speaks for options but with the original calling cert, so thinks GENI Desktop is trying to call log event.

The call to the log service looks like this:
```
                log_options = {}
....
                    self.logging_service.log_event(
                        "%s Added member %s in role %s to %s %s" % \
                            (caller_name, member_name, member_role, text_str, label),
                        attribs, credentials, log_options, session=session)
```

Note that we're not passing along a brand new and empty options dict, so not the speaksfor options.

 _Imported from trac ticket [#325](http://trac.gpolab.bbn.com/chapi/ticket/325),  created by ahelsing on 09-10-2014 at 16:39, last modified: 09-11-2014 at 15:10_

**Comment by tcmitchell** [comment]
Something along these lines will fix the problem:
```
        log_options = {}
        if 'speaking_for' in options:
            log_options['speaking_for'] = options['speaking_for']
```
In other words, just passing along the 'speaking_for' option as surmised in the description.

We should put that in a function so that the logic is in one place and we can quickly readily generate an options dict for a subordinate call to another clearinghouse service.


_Trac comment by tmitchel (github user: tcmitchell) on 09-10-2014 at 17:23_

**Comment by tcmitchell** [comment]
MA also makes calls to the logger with empty options. A convenient spot for a utility method might be DelegateBase, which is a common ancestor to the MA and SA delegates where these logging calls are made.

_Trac comment by tmitchel (github user: tcmitchell) on 09-10-2014 at 17:28_

**Comment by tcmitchell** [comment]
I have replicated the issue by generating a tool certificate, issuing a speaks-for credential allowing that tool to speak for me, and using the client.py tool to call create_slice at the SA.

_Trac comment by tmitchel (github user: tcmitchell) on 09-11-2014 at 14:16_

**Comment by tcmitchell** [comment]
Implemented DelegateBase.subcall_options(options) to generate an options dictionary for subordinate calls from the options dictionary passed in the original call. Replaced log_options empty dict with call to subcall_options() in MA and SA.

_Trac comment by tmitchel (github user: tcmitchell) on 09-11-2014 at 15:10_
