### ISSUE TITLE
create a script to get username from email address

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#329]
Create a script that uses APIs to get a user's username given their email address.

Operators would use this to disable a user whose email is bouncing.

 _Imported from trac ticket [#329](http://trac.gpolab.bbn.com/chapi/ticket/329),  created by ahelsing on 09-30-2014 at 14:31, last modified: 03-31-2015 at 14:16_

**Comment by ahelsing** [comment]
An Admin page that does this (in process) would make this OBE

**Comment by tcmitchell** [comment]
The portal admin page implements this functionality in the 2.34 release of the portal.
