### ISSUE TITLE
Allow multiple CAs for tool certs

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#334]
Allow multiple CAs for clients of ch.geni.net

But then in code, any CA that is not our CA gets directed down only a speaks for path - that is, we only trust our own CA for clients to be actual members. Anyone else is only authorized to be speaking for someone else.

This will allow the PG CA to sign a tool cert for Cloudlab, allowing users to give Cloudlab a speaks for so it can get their GPO registered SSH keys.

 _Imported from trac ticket [#334](http://trac.gpolab.bbn.com/chapi/ticket/334),  created by ahelsing on 10-22-2014 at 20:51, last modified: 12-02-2014 at 14:24_

**Comment by tcmitchell** [comment]
Here is a diff to the apache configuration to allow multiple CAs:
```
$ diff -Naur ch-ssl~ ch-ssl
--- ch-ssl~     2014-09-10 11:09:48.650649347 -0400
+++ ch-ssl      2014-11-12 14:59:51.897341169 -0500
@@ -184,7 +184,7 @@
 
         # Include configuration files for CHAPI clearinghouse services
         SSLOptions +ExportCertData
-        SSLCACertificateFile /usr/share/geni-ch/CA/cacert.pem
+        SSLCACertificateFile /etc/geni-chapi/root-bundle.pem
         # Support cert revocation lists
         SSLCARevocationFile /usr/share/geni-ch/ma/ma-crl.pem
         SSLVerifyClient optional
@@ -269,7 +269,7 @@
         BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
 
         SSLOptions +ExportCertData
-        SSLCACertificateFile /usr/share/geni-ch/CA/cacert.pem
+        SSLCACertificateFile /etc/geni-chapi/root-bundle.pem
         SSLVerifyClient require
         SSLVerifyDepth 3
 
@@ -307,7 +307,7 @@
         BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
 
         SSLOptions +ExportCertData
-        SSLCACertificateFile /usr/share/geni-ch/CA/cacert.pem
+        SSLCACertificateFile /etc/geni-chapi/root-bundle.pem
         SSLVerifyClient optional_no_ca
         SSLVerifyDepth 3
 
```


_Trac comment by tmitchel (github user: tcmitchell) on 11-12-2014 at 15:25_

**Comment by ahelsing** [comment]
Apache config change is tracked here: http://groups.geni.net/syseng/ticket/6364

_Trac comment by ahelsing on 12-02-2014 at 14:24_
