### ISSUE TITLE
opsmon handle_slice_request only returns slice lead

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#338]
The opsmon plugin's handle_slice_request returns an array of members that is only ever the slice lead.

The schema supports returning multiple members, but the plugin is not returning them.

 _Imported from trac ticket [#338](http://trac.gpolab.bbn.com/chapi/ticket/338),  created by ahelsing on 10-30-2014 at 13:51, last modified: 10-31-2014 at 11:15_

**Comment by tcmitchell** [comment]
The lack of slice members is by design for privacy reasons. The clearinghouse shares project lead information about a slice, but will not share private data about members of a slice.

_Trac comment by tmitchel (github user: tcmitchell) on 10-31-2014 at 11:15_
