### ISSUE TITLE
Add federated aggregates: Cloud Lab and Apt

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#343]
Add Cloud Lab and Apt as new Federated aggregates

 _Imported from trac ticket [#343](http://trac.gpolab.bbn.com/chapi/ticket/343),  created by ahelsing on 01-13-2015 at 14:26, last modified: 01-20-2015 at 13:03_

**Comment by ahelsing** [comment]
For utah.cloudlab.us:
 - CloudLab Utah
 - https://boss.utah.cloudlab.us:12369/protogeni/xmlrpc/am/2.0
 - urn:publicid:IDN+utah.cloudlab.us+authority+cm
 - clab-utah

For apt.emulab.net:
 - Apt
 - https://boss.apt.emulab.net:12369/protogeni/xmlrpc/am/2.0
 - urn:publicid:IDN+boss.apt.emulab.net+authority+cm
 - apt


_Trac comment by ahelsing on 01-15-2015 at 14:11_

**Comment by ahelsing** [comment]
Mark notes that our convention is to list site before testbed type, so it would be
 * Utah CloudLab
 * utah-clab
 * Utah Apt
 * utah-apt

Although we don't do this for "plc".

_Trac comment by ahelsing on 01-15-2015 at 14:19_

**Comment by ahelsing** [comment]
added the appropriate nicknames to omni

_Trac comment by ahelsing on 01-16-2015 at 14:23_

**Comment by tcmitchell** [comment]
Apt has been added CloudLab is waiting on the CM cert which has been requested from Utah.

_Trac comment by tmitchel (github user: tcmitchell) on 01-20-2015 at 12:35_

**Comment by tcmitchell** [comment]
CloudLab has been added

_Trac comment by tmitchel (github user: tcmitchell) on 01-20-2015 at 13:03_
