### ISSUE TITLE
Add AL2S aggregate

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#345]
Add AL2S as a production aggregate.
al2s= urn:publicid:IDN+al2s.internet2.edu+authority+am,https://geni-al2s.net.internet2.edu:3626/foam/gapi/2
http://groups.geni.net/geni/wiki/GeniAggregate/I2AL2S

Note that the host does not exist yet, and we don't yet have the certificates.

 _Imported from trac ticket [#345](http://trac.gpolab.bbn.com/chapi/ticket/345),  created by ahelsing on 01-27-2015 at 17:32, last modified: 01-28-2015 at 11:16_

**Comment by ahelsing** [comment]
first cut at data pushed on tkt345-al2s. 

_Trac comment by ahelsing on 01-27-2015 at 17:34_

**Comment by tcmitchell** [comment]
When the aggregate appears on the network we can pull the certificate with this command:
```
openssl s_client -debug -prexit -showcerts -connect geni-al2s.net.internet2.edu:3626
```
More info about federating with FOAM aggregates is available at:
```
http://groups.geni.net/syseng/wiki/SwClearinghouse/Federation/FOAM
```


_Trac comment by tmitchel (github user: tcmitchell) on 01-28-2015 at 09:31_

**Comment by ahelsing** [comment]
got the new certs from Luke. Added those and pushed to develop

_Trac comment by ahelsing on 01-28-2015 at 11:08_

**Comment by ahelsing** [comment]
Note this host trusts cascade for testing purposes.

_Trac comment by ahelsing on 01-28-2015 at 11:16_
