### ISSUE TITLE
Makefile should install chapi git hash in /etc/geni-chapi/geni-chapi-githash

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#35]
The proto-ch.git make process installs a git hash in /etc/geni-ch/geni-ch-githash.  The chapi.git make process should do similarly --- i assume it should put the chapi-specific git hash under /etc/geni-chapi/, but i don't feel strongly.

 _Imported from trac ticket [#35](http://trac.gpolab.bbn.com/chapi/ticket/35),  created by chaos on 11-12-2013 at 16:43, last modified: 11-20-2013 at 14:49_

**Comment by tcmitchell** [comment]
Done. Installed as `/etc/geni-chapi/geni-chapi-githash`.

_Trac comment by tmitchel (github user: tcmitchell) on 11-20-2013 at 14:49_
