### ISSUE TITLE
CHAPI installs a python module in /usr/local/bin/util/

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#36]
It looks like CHAPI installs:
```
/usr/local/bin/util/chapi.py
/usr/local/bin/util/__init__.py
```
At a glance, those also seem to be executables and not to have main() routines, so i think they're meant to be included as modules.  I think they should be (a) non-executable, and (b) in a lib directory, preferably under a geni-ch or geni-chapi specific path, not under /usr/local/bin

 _Imported from trac ticket [#36](http://trac.gpolab.bbn.com/chapi/ticket/36),  created by chaos on 11-12-2013 at 17:37, last modified: 11-15-2013 at 08:10_

**Comment by tcmitchell** [comment]
`proto-ch` was installing these files. They are no longer installed.

_Trac comment by tmitchel (github user: tcmitchell) on 11-14-2013 at 17:20_
