### ISSUE TITLE
Bug report: lookup SLICE with match on SLICE_EXPIRED fails

### ISSUE THREAD

**Issue by wvdemeer** [GENI-NSF/geni-ch#394]
A SLICE lookup call with both a match on SLICE_URN, and a match on "SLICE_EXPIRED: false", causes a server error.

Below is an example of the problem.

Request "lookup" call:
```json
[
"SLICE",
[
   {
      "geni_type": "geni_sfa",
      "geni_version": "3",
      "geni_value": "... credential removed because not relevant ..."
      }
   ],
{
   "match": {
                 "SLICE_URN": [
                        "urn:publicid:IDN+ch.geni.net:ipv6proxy+slice+dummy"
                        ],
                 "SLICE_EXPIRED": false
                 }
   }
]
```

Server Reply:
```json
{
"output": "[SERVER] SERVER_ERROR ('bool' object has no attribute 'lower')",
"code": 101,
"value": ""
}
```

I guess the server is expecting a string that contains the text "false", but a boolean is given. However, the API requires a boolean here.

**Comment by tcmitchell** [comment]
I was able to verify this issue with `client.py`. The BOOLEAN parsing in `ArgumentCheck.py` required the value to be in the set ['t', 'f', 'true', 'false']. It now allows values of type bool as well.
