### ISSUE TITLE
Project creation times are iso8601 encoded, but other dates are not

### ISSUE THREAD

**Issue by nbastin** [GENI-NSF/geni-ch#397]
The CHAPI2 docs only have a definition of what a "DATETIME" is, and it states:

"String representing a date/time in RFC3339 format ( http://tools.ietf.org/html/rfc3339)."

And indeed, the CH will only accept dates in these formats.  However, sometimes it *returns* dates as ```dateTime.iso8601``` types, not strings (and sometimes it doesn't):

```
<name>PROJECT_CREATION</name>
<value><dateTime.iso8601>20150817T11:23:38</dateTime.iso8601></value>
</member>
<member>
<name>PROJECT_UID</name>
<value><string>dd3d03f2-13b6-4928-9243-f2df073dae66</string></value>
</member>
<member>
<name>PROJECT_EXPIRED</name>
<value><nil/></value></member>
<member>
<name>PROJECT_EXPIRATION</name>
<value><string>2015-08-19T04:23:29Z</string></value>
</member>
```

Honestly I'd prefer that all dates were in ```dateTime.iso8601``` format, but either way it should be consistent across the entire API, instead of each developer having to test each (undocumented) return on their own.

**Comment by tcmitchell** [comment]
Many API functions invoke `construct_result_row` (dbutils.py) which converts dates to strings. It would be helpful to know what call(s) are not properly converting datetime instances to strings. `lookup_projects` (and thus `lookup("PROJECT", ...)`), for instance, calls `construct_result_row`.

What API function were you invoking to get the above results?

**Comment by nbastin** [comment]
That comes from `create` for `PROJECT`.

**Comment by tcmitchell** [comment]
`SAv1PersistentImplementation.finish_create()` should convert dates to strings when creating the return structure. Verify that's ok for `create_slice` as well as `create_project`.

**Comment by nbastin** [comment]
Slice creation has the same problem:

```
{'SLICE_CREATION': <DateTime '20150831T00:14:03' at 7f3ecdd3fb48>,
 'SLICE_DESCRIPTION': None,
 'SLICE_EXPIRATION': <DateTime '20150830T19:13:56' at 7f3ecdd3fb00>,
 'SLICE_EXPIRED': None,
 'SLICE_NAME': 'chtest-1',
 'SLICE_PROJECT_URN': 'urn:publicid:IDN+ch.geni.net+project+vts-infra',
 'SLICE_UID': '60e3e5de-cc27-4971-8f81-2af71eb3899f',
 'SLICE_URN': 'urn:publicid:IDN+ch.geni.net:vts-infra+slice+chtest-1',
 '_GENI_PROJECT_UID': '10c88fc8-9d57-4971-8820-5b14323557f5',
 '_GENI_SLICE_EMAIL': None,
 '_GENI_SLICE_OWNER': '8a447f06-8bd5-4f32-8fd6-1a3528e7fa37'}
```
