### ISSUE TITLE
ARGUMENT_ERROR is over-broad

### ISSUE THREAD

**Issue by nbastin** [GENI-NSF/geni-ch#398]
If you try to delete a project at the GPO CH, you can't - as a matter of CH policy - but instead of having any way to tell you this the CH just returns ARGUMENT_ERROR:

```
{'output': '[ARGUMENT] ARGUMENT_ERROR (method delete not supported for PROJECT)', 'code': 3, 'value': None}
```

Unfortunately this makes it practically impossible for a tool to know whether the format of a given argument was bad, or whether there's some unsupported operation.  Given a suitably vague reading of the docs this may be interpreted as being legal, but it's certainly not helpful.  It would be much better if there was a separate UNSUPPORTED_OPERATION error to indicate otherwise legal operations that are not supported at this CH instance.

**Comment by tcmitchell** [comment]
There is a `NotImplementedError`, use that instead of argument error.
