### ISSUE TITLE
_GENI_PROJECT_EMAIL contents are polluted with example.com

### ISSUE THREAD

**Issue by nbastin** [GENI-NSF/geni-ch#399]
The data returned by ```lookup``` on projects includes the field ```_GENI_PROJECT_EMAIL```, whose contents are in violation of RFC 2606 and cause issues with software that conforms to RFC 6761:

```
   2.  Application software SHOULD NOT recognize example names as
       special and SHOULD use example names as they would other domain
       names.

   3.  Name resolution APIs and libraries SHOULD NOT recognize example
       names as special and SHOULD NOT treat them differently.  Name
       resolution APIs SHOULD send queries for example names to their
       configured caching DNS server(s).
```

This field, regardless of its' use, should not contain email address with the domain ```example.com```.

**Comment by ahelsing** [comment]
We should stop returning this field with it's bogus content
