### ISSUE TITLE
Integrate with AMsoil v0.4

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ch#40]
AMsoil v0.4 has been released. It may have all the local fixes, or at least some of them.

Upgrade chapi to work with AMsoil v0.4.

 _Imported from trac ticket [#40](http://trac.gpolab.bbn.com/chapi/ticket/40),  created by tmitchel on 11-14-2013 at 13:22, last modified: 07-15-2014 at 13:03_

**Comment by MarshallBrinn** [comment]
AMSoil is no longer supported. We will be sticking with the currently installed version.
