### ISSUE TITLE
"lookup" needs to allow "PROJECT_NAME" match for projects

### ISSUE THREAD

**Issue by nbastin** [GENI-NSF/geni-ch#409]
`PROJECT_NAME` is required for creating a project, but you can't lookup projects using it.  This means that given a project name (all the user has, in many cases) it's for all intents and purposes impossible to reliably find its URN (and thus cannot create slices), as the format of the URN is not mandated by the spec.  This requires that every tool write a heuristic for decomposing the URNs from each clearinghouse (which may never actually give you a relationship to a project name).

The only call that ever knows the URN for a name is `create`, and if you didn't create the project you can never get this information.

**Comment by tcmitchell** [comment]
The portal uses `lookup_projects` with a match criteria of `PROJECT_NAME` to look up projects by name. Is that a possible avenue for your use case?

I assume the issue here is specific to the `lookup` call? In other words, `lookup` does not accept `PROJECT_NAME` as a match criteria? A quick glance at the clearinghouse code shows SA `lookup` calling `lookup_projects` under the covers. Do you get an error when you try to use PROJECT_NAME in the match criteria?

**Comment by nbastin** [comment]
If I use PROJECT_NAME in the filter, it returns the entire set of projects in the CH (even if mine is valid and should be matched), and uses a format completely different from `lookup_projects_for_member`:

```
...
           'urn:publicid:IDN+ch.geni.net+project+VNode-Federation': {'PROJECT_CREATION': '2015-07-17T02:52:09Z',
                                                                     'PROJECT_DESCRIPTION': 'International Federation b/w US and Japan based on Slice Exchange Point (SEP)',
                                                                     'PROJECT_EXPIRATION': '2017-03-31T23:59:59Z',
                                                                     'PROJECT_EXPIRED': False,
                                                                     'PROJECT_NAME': 'VNode-Federation',
                                                                     'PROJECT_UID': '0f1e4a3f-39ab-45f0-88f2-cfb30fe4471b',
                                                                     'PROJECT_URN': 'urn:publicid:IDN+ch.geni.net+project+VNode-Federation',
                                                                     '_GENI_PROJECT_EMAIL': 'project-VNode-Federation@example.com',
                                                                     '_GENI_PROJECT_OWNER': 'c707cdc7-533d-4cc9-a3b5-3d6a9966a130'},
           'urn:publicid:IDN+ch.geni.net+project+VTS-experiments': {'PROJECT_CREATION': '2014-05-15T02:43:01Z',
                                                                    'PROJECT_DESCRIPTION': 'To explore which experiments in our lab can utilize VTS resources',
                                                                    'PROJECT_EXPIRATION': '2016-08-31T23:59:59Z',
                                                                    'PROJECT_EXPIRED': False,
                                                                    'PROJECT_NAME': 'VTS-experiments',
                                                                    'PROJECT_UID': 'fd766370-ed68-4b1a-9aeb-d089abfe0320',
                                                                    'PROJECT_URN': 'urn:publicid:IDN+ch.geni.net+project+VTS-experiments',
                                                                    '_GENI_PROJECT_EMAIL': 'project-VTS-experiments@example.com',
                                                                    '_GENI_PROJECT_OWNER': '5a86c6c3-18d4-4f81-a4e5-37d755f013e3'},
...
```

Actually, I can't get the match filter on lookup to work at all...everything I do returns the whole list.

**Comment by nbastin** [comment]
It appears I'm not using the proper "filter" option...

**Comment by nbastin** [comment]
It does work if you supply `PROJECT_NAME` inside the proper option...

The docs should either be updated to reflect this (match says "No" right now for project_name), or there maybe should be separate docs for this CH versus the spec.

**Comment by nbastin** [comment]
It would be nice if this output was consistent across all of the lookup calls.

**Comment by tcmitchell** [comment]
The [API documentation](http://groups.geni.net/geni/wiki/CommonFederationAPIv2) has been updated.
