### ISSUE TITLE
Project page shows usernames not pretty names

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#41]
On project page the list of project members, other than the current user shows only the username not the other user's Pretty Name

 _Imported from trac ticket [#41](http://trac.gpolab.bbn.com/chapi/ticket/41),  created by ahelsing on 11-14-2013 at 14:08, last modified: 11-19-2013 at 11:34_

**Comment by ahelsing** [comment]
names are correct on edit-project

_Trac comment by ahelsing on 11-14-2013 at 14:11_

**Comment by tcmitchell** [comment]
This was a problem in proto-ch ma_client.php, not in chapi. It is fixed.

_Trac comment by tmitchel (github user: tcmitchell) on 11-19-2013 at 11:34_
