### ISSUE TITLE
"lookup" should return all attributes of an object

### ISSUE THREAD

**Issue by nbastin** [GENI-NSF/geni-ch#410]
Projects have 7 attributes (urn, uid, creation, expiration, expired, name, description), but `lookup` only returns 4 of them:

```
{'EXPIRED': False,
 'PROJECT_ROLE': 'ADMIN',
 'PROJECT_UID': '455d79f8-d2cb-4de9-8c4c-3786edff0d01',
 'PROJECT_URN': 'urn:publicid:IDN+ch.geni.net+project+VTSINJACKS'}
```

There appears to be no way to get the rest of the attributes after a resource is created (at creation time it returns all the fields, but that's not generally helpful to tools that come along later).

**Comment by tcmitchell** [comment]
That's a very odd return value because `PROJECT_ROLE` would be affiliated with a user, not a project. Can you send the full arguments of your call to `lookup` so that we can understand this better?

**Comment by tcmitchell** [comment]
Ah - this is likely a call to `lookup_for_member('PROJECT', ...)` or `lookup_projects_for_member()`. Those calls appear to return exactly the four fields mentioned in the description. Is that correct? Or was this actually a call to `lookup()`?

**Comment by nbastin** [comment]
It turns out it was probably a call to `lookup_projects_for_member` - that list is smaller (which is why we use it), but doesn't contain the information we generally need.

**Comment by tcmitchell** [comment]
The [API documentation](http://groups.geni.net/geni/wiki/CommonFederationAPIv2) states that `lookup_for_member` (the v2 replacement for `lookup_projects_for_member` "Returns list of {PROJECT_URN, PROJECT_ROLE} dictionaries for projects to which a given member belongs".

The `lookup` method does return all attributes of a project.
