### ISSUE TITLE
"lookup" doesn't filter based on URN for Projects

### ISSUE THREAD

**Issue by nbastin** [GENI-NSF/geni-ch#412]
If you supply a URN that doesn't exist to `lookup` for projects, it returns to you every project in the clearinghouse, instead of none.

**Comment by nbastin** [comment]
This was user error, it seems to work fine:

```
{'code': 3,
 'output': "[ARGUMENT] ARGUMENT_ERROR (Unknown project urns: [['urn:publicid:IDN+ch.geni.net+project+floobmagoo']])",
 'value': None}
```

The problem is that if you typo `match` or fail to supply it, the endpoint doesn't complain, it just gives you everything.

**Comment by tcmitchell** [comment]
User error, closing.
