### ISSUE TITLE
Would be nice to be able to filter on lookup_for_member

### ISSUE THREAD

**Issue by nbastin** [GENI-NSF/geni-ch#415]
Particularly for slices, this list can be enormous and eat up a lot of bytes.  It would be nice if I could just filter for slices I created (or at least slices for which I am `LEAD`, which is not the same, but may be easier to figure out).

**Comment by tcmitchell** [comment]
This clearinghouse has some extra non-standard fields that it can use for match criteria. Can you try `_GENI_SLICE_OWNER` as the match criteria to find slices that you created? The value should be a UUID, not a URN.

**Comment by nbastin** [comment]
Does `lookup_for_member` take `match` criteria?  Or do I need to go back to bare `lookup` for this?

(I find the docs very hard to understand, at least until I finally figure them out, and then they at least make sense, but it's not easy to figure out what they mean from zero.. :-))

**Comment by tcmitchell** [comment]
Yes, it looks like `lookup_for_member` takes `match` criteria.

**Comment by tcmitchell** [comment]
I confirmed that I can supply `_GENI_SLICE_OWNER` in the match option with my UUID (extracted from my certificate) to list projects that I LEAD (i.e. created).
