### ISSUE TITLE
Programmatic interface to add members to projects

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-ch#423]
It would be useful to have a programmatic interface to add members to a project, basically expose the bulk add functionality through the ch api. That way in classes the professors can automate this process without necessarily having to go through the GUI. 

If the person that is trying to add users to a project is not a lead or admin, the call can return a not authorized error.

**Comment by tcmitchell** [comment]
All of the programmatic APIs used by the portal are already exposed. That's exactly how the portal implements features. There is an existing script, `bin/geni-add-project-member`, that adds a single member to a project. It relies on `bin/chapiclient/chapi.py`. Feel free to use those to build a bulk add script if you so desire. This script uses the same clearinghouse APIs that the portal's bulk add feature uses.

**Comment by ahelsing** [comment]
You could also do this as a pull request on geni-tools, creating a method in `framework_chapi` modeled off of `add_member_to_slice`. You want to call `modify_project_membership(project_urn, creds, options)`, where `$options['members_to_add']` is a dictionary of of urn->role. 

Note that in the portal, when you add someone to a project, you automatically add them to the proper irods group. 
The relevant PHP code is in geni-portal under lib/php/pa_client.php: modify_project_membership.
