### ISSUE TITLE
error editing description of a project

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#44]
```
[SERVER] SERVER_ERROR ((DataError) invalid input syntax for type timestamp: "" LINE 1: ...roject SET project_purpose=E'testing', expiration=E_ WHERE ... ^ 'UPDATE pa_project SET project_purpose=%(project_purpose)s, expiration=%(expiration)s WHERE pa_project.project_name = %(project_name_1)s' {'project_name_1': 'ahscaletest', 'project_purpose': 'testing', 'expiration': _})
```

 _Imported from trac ticket [#44](http://trac.gpolab.bbn.com/chapi/ticket/44),  created by ahelsing on 11-14-2013 at 14:11, last modified: 11-19-2013 at 11:55_

**Comment by tcmitchell** [comment]
To reproduce, click the edit button on a project, then edit the project description ("purpose") of a project and leave the expiration blank. Here is the error in prettier form:
```
[SERVER] SERVER_ERROR ((DataError) invalid input syntax for type timestamp: ""
  LINE 1: ...pa_project SET project_purpose=E'foo', expiration=E_ WHERE ... ^ 'UPDATE pa_project
  SET project_purpose=%(project_purpose)s, expiration=%(expiration)s
  WHERE pa_project.project_name = %(project_name_1)s'
  {'project_name_1': 'CHAPI', 'project_purpose': 'foo', 'expiration': _})
```

_Trac comment by tmitchel (github user: tcmitchell) on 11-19-2013 at 11:38_

**Comment by tcmitchell** [comment]
If expiration is populated on the form, the update succeeds. The SA needs to handle an empty expiration.

_Trac comment by tmitchel (github user: tcmitchell) on 11-19-2013 at 11:40_

**Comment by tcmitchell** [comment]
Fixed. Check for an empty expiration and convert to None for insertion in DB.

_Trac comment by tmitchel (github user: tcmitchell) on 11-19-2013 at 11:55_
