### ISSUE TITLE
Remove dependency on AMsoil

### ISSUE THREAD

**Issue by MarshallBrinn** [GENI-NSF/geni-ch#473]
AMsoil is no longer supported and we should rearchitect the CH web service to no longer depend on it.

**Comment by MarshallBrinn** [comment]
We have an inconsistency between the chapi.ini files and the Parameters.py(.in) files. Both contain logic for defaults and Parameters.py ignores any entries in chapi.ini that aren't known to it.

	- Change Parameters.py.in to Parameters.py, providing default values (which can be overridden) for some variables and no default values (which must be provided in chapi.ini) for others.

	- Remove variables that are no longer needed from Parameters.py, as well as chapi.ini.tmpl.

	- Print an error message (but don’t exit) if you parse a chapi.ini file with a variable that is not registered in Parameters.ini

**Comment by tcmitchell** [comment]
Closed by #483
