### ISSUE TITLE
ABACManager sometimes calls itself via a subprocess invocation

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ch#489]
There are two places in `ABACManager.py` where ABACManager is invoked as a subprocess and the standard out is parsed for information. (search for `__file__` for the two locations)

This seems odd since we're already in ABACManager.py. Is this really the way to go? Or should the ABACManager shell invocations be turned into functional invocations instead? If there's a good rationale for this, then it's fine.

**Comment by MarshallBrinn** [comment]
I believe this is fixed in the re-work of geni-ch to remove libabac. There should be no more support for calling ABACManager subprocesses from within ABACManager. This was only done to go around a problem with memory management created by the libabac library itself.

**Comment by tcmitchell** [comment]
Reopened so that it is closed by the relevant pull request.
