### ISSUE TITLE
/usr/share/geni-ch/chapi contains git artifacts

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#5]
The `/usr/share/geni-ch/chapi/` directory is installed by `install_chapi` with the git artifacts of its various component repositories attached, including `.gitignore` and `.git/`.  Perhaps the tar commands could be modified to exclude git artifacts.

 _Imported from trac ticket [#5](http://trac.gpolab.bbn.com/chapi/ticket/5),  created by chaos on 11-07-2013 at 14:22, last modified: 11-13-2013 at 17:26_

**Comment by ahelsing** [comment]
where we are doing a straight tar of a git directory, we should use git archive. Something like `git archive --prefix=module-VERSION/ HEAD > module-VERSION.tar`

_Trac comment by ahelsing on 11-07-2013 at 14:37_

**Comment by tcmitchell** [comment]
The git turds are gone. The installer no longer uses git at all. It uses the current working directory instead. Dependencies that had been in the proto-ch directory are now in the chapi directory. AMsoil is now installed from a versioned tarfile hosted on www.gpolab.bbn.com.

_Trac comment by tmitchel (github user: tcmitchell) on 11-13-2013 at 17:26_
