### ISSUE TITLE
omni does not play nice with apache deflate module

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ch#50]
When the apache deflate module is enabled omni gets confused about the output from PGCH and gets errors like:
```
IncompleteRead(313 bytes read, 765 more expected)
```

Disabling deflation of mime type `text/xml` fixes the issue.

Is there a way to disable deflation only in the relevant servers (ch:443, ch:8443)? Or do we need to disable this globally?

 _Imported from trac ticket [#50](http://trac.gpolab.bbn.com/chapi/ticket/50),  created by tmitchel on 11-15-2013 at 16:01, last modified: 11-18-2013 at 09:38_

**Comment by ahelsing** [comment]
I haven't been keeping track of things, but the last time i reinstalled tau-ceti (a few days ago now), the installer modified
```
/etc/apache2/mods-available/deflate.conf
```
and disabled deflation of XML globally.  I don't know if there's a way to do it non-globally, but just mentioning that the installer used to do it globally in case that got lost recently.

_Trac comment by chaos on 11-15-2013 at 16:32_

**Comment by tcmitchell** [comment]
It didn't get "lost". We removed it because the supporting use case no longer required it. It turns out omni does require it. It will be restored.

_Trac comment by tmitchel (github user: tcmitchell) on 11-15-2013 at 16:35_

**Comment by tcmitchell** [comment]
The apache deflate module is now adjusted on install. Only text/xml is removed. Formerly, both text/xml and text/html were removed, but I think we want to maintain deflation of text/html.

_Trac comment by tmitchel (github user: tcmitchell) on 11-18-2013 at 09:38_
