### ISSUE TITLE
You're forced to authorize the portal in order to use the non-GENI-API parts of the portal

### ISSUE THREAD

**Issue by nbastin** [GENI-NSF/geni-ch#541]
I think you should be able to see the general portal interface, and see your projects and such, without authorizing the portal to act as you.  If I give the portal a CSR and it signs that, I can still use the portal (even though it *can't* act as me), but if I allow the portal to generate my keys and then don't authorize it to act as me, I can't access the portal at all.

**Comment by tcmitchell** [comment]
I think this issue should be raised on the [geni-portal](https://github.com/GENI-NSF/geni-portal) repository. It is not a clearinghouse issue. If you agree, please close this one and create an issue there.

**Comment by nbastin** [comment]
I knew something felt wrong about where I was putting this...moving it.  :-)
