### ISSUE TITLE
ucdavis-eg site no longer exists

### ISSUE THREAD

**Issue by luisanevers** [GENI-NSF/geni-ch#564]
The site ucdavis-eg no longer exists. The following clean up is needed:

1. Remove from up/down status page in portal: https://portal.geni.net/amstatus.php
2 . Remove from the list of EG sites when Adding Resources to a slice in the portal.

Additionally site is being removed from agg_nick_cache see https://github.com/GENI-NSF/geni-tools/issues/913

**Comment by tcmitchell** [comment]
Appearance on the portal, as documented in the description above, is controlled by entries in the service registry and the Jacks context. Here are the real tasks:

- [ ] [Remove ExoGENI UC Davis from geni-lib](https://bitbucket.org/barnstorm/geni-lib/pull-requests/172)
- [x] [Remove ExoGENI UC Davis from the Jacks context building script](https://github.com/Jacks-GENI/jacks-context/pull/16)
- [ ] Remove ExoGENI UC Davis from the service registry
    * Remove certificates
    * Remove from aggregate data CSV file
    * Remove from Makefile
    * Remove from RPM spec file
- [ ] Document SQL commands to remove ExoGENI UC Davis from a running service registry

**Comment by tcmitchell** [comment]
UC Davis ExoGENI was removed from the service registry as part of today's clearinghouse update. It will still appear on the map until the map data is rebuilt.
