### ISSUE TITLE
don't install nginx

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#6]
Right now, the CHAPI installation process (`install_ch` in particular) installs the nginx package.  Don't install nginx unless it is actually needed.

 _Imported from trac ticket [#6](http://trac.gpolab.bbn.com/chapi/ticket/6),  created by chaos on 11-07-2013 at 15:12, last modified: 11-11-2013 at 10:24_

**Comment by tcmitchell** [comment]
`nginx` has been removed from the installation.

Additionally, `pika` was removed from the installation. Version numbers were added for other python packages installed via easy_install.


_Trac comment by tmitchel (github user: tcmitchell) on 11-11-2013 at 10:24_
