### ISSUE TITLE
sa_slice is not updated when member roles change

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#66]
_Imported from trac ticket [#66](http://trac.gpolab.bbn.com/chapi/ticket/66),  created by phelinek on 11-20-2013 at 17:47, last modified: 11-21-2013 at 10:52_

**Comment by ahelsing** [comment]
This is actually confusing because the field is called "owner_id" not "lead_id".  Is the lead also the owner?  If so then owner_id should change.  But if owner means something different then maybe not. 

_Trac comment by phelinek on 11-20-2013 at 17:58_

**Comment by MarshallBrinn** [comment]
I think 'owner_id' is somewhat obsolete and redundant: we've talked about getting rid of it. In any event it shouldn't contain different information than the lead member.

_Trac comment by mbrinn (github user: MarshallBrinn) on 11-21-2013 at 07:05_

**Comment by ahelsing** [comment]
Slice owner in this case is exactly the slice member who is the slice lead.

_Trac comment by ahelsing on 11-21-2013 at 09:15_

**Comment by ahelsing** [comment]
added code to update owner_id field in sa_slice when slice lead changes

_Trac comment by phelinek on 11-21-2013 at 10:52_
