### ISSUE TITLE
wimax button does not appear

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#67]
The wimax button should appear if the user has the enable_wimax_button attribute. It does not.

 _Imported from trac ticket [#67](http://trac.gpolab.bbn.com/chapi/ticket/67),  created by ahelsing on 11-21-2013 at 14:36, last modified: 11-28-2013 at 10:04_

**Comment by MarshallBrinn** [comment]
The reason we're not seeing the WIMAX button is that the CHAPI MA doesn't pass this along with any of its "lookup_*_member_info" calls. 

Here's a list of all the attribute types on cascade that we DON'T currently return. Some of these look bogus, some look real. I've indicated next  to these which I plan to return and where.


reference				---- NOT RETURNING ---
wimax_username		IDENTIFYING
reason					--- NOT RETURNING ---
enable_irods			PUBLIC
enable_wimax			PUBLIC
enable_wimax_button	PUBLIC
panther_inside_cerrt		--- NOT RETURNING ---
eppn_disabled			--- NOT RETURNING ---
gemini-user				PUBLIC
email_address_duplicate	--- NOT_RETURNING ----
irods_username			IDENTIFYING
orig_email_address		--- NOT RETURNING ----
eppn_duplicate			--- NOT_RETURNING ---


Let me know if any of this doesn't sound right: these changes are easy to make. Meanwhile I'll proceed along these lines.

But bear in mind that when we add a new attribute type, we need to add it into MA_constants (and in some cases to MAv1Implementation) and not just into the database scripts.

- Marshall

_Trac comment by mbrinn (github user: MarshallBrinn) on 11-22-2013 at 07:30_

**Comment by ahelsing** [comment]
Looks fine.

reference and reason are extra information: who can vouch for you and why you want to use GENI / be a lead. Not important now.



_Trac comment by ahelsing on 11-22-2013 at 12:50_

**Comment by MarshallBrinn** [comment]
THe add_project_attribute and remove_project_attribute methods weren't implemented on the PHP or PY side. Now they're implemented and checked in and these MA attributes are now passed back:

wimax_username : IDENTIFYING
irods_username : IDENTIFYING
enable_wimax : PUBLIC
enable_wimax_button : PUBLIC
enable_irods : PUBLIC

The irons and wimax stuff SEEMS to work but I need someone more fluent in these portal functions to validate that they're working. 



_Trac comment by mbrinn (github user: MarshallBrinn) on 11-22-2013 at 14:14_

**Comment by MarshallBrinn** [comment]
This is fixed and checked in: if you have the enable_wimax_button attribute you should see the button.

_Trac comment by mbrinn (github user: MarshallBrinn) on 11-28-2013 at 10:04_
