### ISSUE TITLE
cannot view expired project

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#68]
As project lead, expire a project.
You get a warning that you have no privileges to view the project.
You can see it on the projects page as an expired project. But clicking on it gets you kicked back to the home page with that warning

 _Imported from trac ticket [#68](http://trac.gpolab.bbn.com/chapi/ticket/68),  created by ahelsing on 11-21-2013 at 15:07, last modified: 11-21-2013 at 16:36_

**Comment by MarshallBrinn** [comment]
Fixed in CHAPI - remove the "expired == 'f'" clause in get_members in SAv1PersistentImplementation so you can always ask for members of a project or slice, expired or not.

_Trac comment by mbrinn (github user: MarshallBrinn) on 11-21-2013 at 16:36_
