### ISSUE TITLE
remove obsolete apache config lines

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#7]
The install script leaves obsolete lines in the apache config:
```
	Include /usr/share/geni-ch/sa/apache2.conf
	Include /usr/share/geni-ch/ma/apache2.conf
	Include /usr/share/geni-ch/pa/apache2.conf
	Include /usr/share/geni-ch/sr/apache2.conf
	Include /usr/share/geni-ch/cs/apache2.conf
	Include /usr/share/geni-ch/logging/apache2.conf
```

 _Imported from trac ticket [#7](http://trac.gpolab.bbn.com/chapi/ticket/7),  created by ahelsing on 11-07-2013 at 16:02, last modified: 11-14-2013 at 13:08_
   CCing: chaos@...

**Comment by tcmitchell** [comment]
Done.

_Trac comment by tmitchel (github user: tcmitchell) on 11-14-2013 at 13:08_
