### ISSUE TITLE
email should be sent when creating a new project

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#79]
The old SA sent email to the admins when a project was created.

 _Imported from trac ticket [#79](http://trac.gpolab.bbn.com/chapi/ticket/79),  created by ahelsing on 11-26-2013 at 11:58, last modified: 12-04-2013 at 16:27_

**Comment by ahelsing** [comment]
The old SA also sent mail when people were added to projects.  Does the new one?

_Trac comment by chaos on 11-26-2013 at 13:39_

**Comment by ahelsing** [comment]
see #33

_Trac comment by ahelsing on 11-26-2013 at 17:03_

**Comment by ahelsing** [comment]
When creating a project, old code:
```
 $msg = "Created project: $project_name with lead $lead_name";
  if ($lead_id != $signer_id) {
    $msg = $signer_urn . " " . $msg;
  }
  if (parse_urn($message->signer_urn, $chname, $t, $n)) {
    $msg = $msg . " on CH $chname";
  }
  mail($portal_admin_email, "New GENI CH project created", $msg);
```


_Trac comment by ahelsing on 12-03-2013 at 12:39_

**Comment by tcmitchell** [comment]
There are some documented shortcomings in the PHP-based emails that we should account for in the new chapi emails:
 * [Don't impersonate users](http://trac.gpolab.bbn.com/proto-ch/ticket/879)
 * [Set some additional headers to play nice with others](http://trac.gpolab.bbn.com/proto-ch/ticket/871)
 * [Set some additional headers to play nice with others redux](http://trac.gpolab.bbn.com/proto-ch/ticket/686)


_Trac comment by tmitchel (github user: tcmitchell) on 12-04-2013 at 09:04_
