### ISSUE TITLE
SA must check timezone

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#91]
slice expirations must be in UTC. update_slice does not check for this and should

Does the federation API require that of project expirations as well?

 _Imported from trac ticket [#91](http://trac.gpolab.bbn.com/chapi/ticket/91),  created by ahelsing on 11-27-2013 at 06:48, last modified: 12-02-2013 at 17:26_

**Comment by MarshallBrinn** [comment]
I put a fix for this general problem in the ArgumentCheck class. Any datetme that comes in is automatically turned into naive UTC (that is, changed to UTC and stripped of the tzinfo information). So if a time comes in without TZ info, it is assumed to be UTC. If it comes in with a different TZ, it is converted to UTC and then replaced in the 'fields' part of the query. Tested on a range of different calls that take date time arguments.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-01-2013 at 07:50_
