### ISSUE TITLE
multiple entries for LEAD and OPERATOR in ma_member_attributes

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#92]
_Imported from trac ticket [#92](http://trac.gpolab.bbn.com/chapi/ticket/92),  created by somebody on 11-27-2013 at 11:00, last modified: 07-11-2014 at 10:40_

**Comment by ahelsing** [comment]
migrate_assertions.sql does an insert each time it is run. So if you run the install script more than once, you will get multiple entries.


_Trac comment by ahelsing on 12-04-2013 at 16:30_

**Comment by tcmitchell** [comment]
Migration is complete, this script is no longer necessary.

_Trac comment by tmitchel (github user: tcmitchell) on 07-11-2014 at 10:40_
