### ISSUE TITLE
avoid extra SQLalchemy sessions

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#95]
In general, there should be 1 SQLAlchemy session per API method invocation.

Certainly though, there should only be one per function

Look for examples of this and fix them

 _Imported from trac ticket [#95](http://trac.gpolab.bbn.com/chapi/ticket/95),  created by ahelsing on 11-28-2013 at 06:55, last modified: 12-12-2013 at 15:40_

**Comment by ahelsing** [comment]
fixed a couple instances. I _believe_ there are no more examples where there are 2 sessions in the same method. However, there may be methods that open a session and call other methods which also open a session.


_Trac comment by ahelsing on 11-28-2013 at 07:30_

**Comment by MarshallBrinn** [comment]
This was fixed as part of the changes for ticket #117.

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-12-2013 at 15:40_
