### ISSUE TITLE
catch SQLalchemy exceptions and rollback

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#96]
When doing any DB modifications, we should be wrapping the call in a try/except so we can do a rollback.

That is, code should be doing something like this:
```
session = self.db.getSession()
try:
 q = session.query(....)
 q.update(.....)
 q.commit()
except
 session.rollback()
 raise # And maybe here we want to raise a nicer exception?
finally
  session.close()

```

 _Imported from trac ticket [#96](http://trac.gpolab.bbn.com/chapi/ticket/96),  created by ahelsing on 11-28-2013 at 06:57, last modified: 12-12-2013 at 15:39_

**Comment by MarshallBrinn** [comment]
Fixed with changes to ticket #117. All calls are caught and sessions closed (with rollback or commit depending on error).

_Trac comment by mbrinn (github user: MarshallBrinn) on 12-12-2013 at 15:39_
